/**
* @project: baregl
* @author: Adrien Givry
* @licence: MIT
*/

#include <baregl/Context.h>

#include <concepts>
#include <span>
#include <vector>

#include <baregl/debug/Assert.h>
#include <baregl/debug/Log.h>
#include <baregl/detail/Types.h>
#include <baregl/detail/glad/glad.h>
#include <baregl/math/Conversions.h>
#include <baregl/utils/BitmaskOperators.h>
#include <baregl/utils/EnumMapper.h>

namespace
{
	uint32_t g_contextCount = 0u;

	void GLDebugMessageCallback(uint32_t p_source, uint32_t p_type, uint32_t p_id, uint32_t p_severity, int32_t p_length, const char* p_message, const void* p_userParam)
	{
		// Ignore non-significant error/warning codes
		if (p_id == 131169 || p_id == 131185 || p_id == 131218 || p_id == 131204)
		{
			return;
		}

		std::string output = "OpenGL Debug Message:\n";
		output += "Debug message (" + std::to_string(p_id) + "): " + p_message + "\n";

		switch (p_source)
		{
		case GL_DEBUG_SOURCE_API:				output += "Source: API";				break;
		case GL_DEBUG_SOURCE_WINDOW_SYSTEM:		output += "Source: Window System";		break;
		case GL_DEBUG_SOURCE_SHADER_COMPILER:	output += "Source: Shader Compiler";	break;
		case GL_DEBUG_SOURCE_THIRD_PARTY:		output += "Source: Third Party";		break;
		case GL_DEBUG_SOURCE_APPLICATION:		output += "Source: Application";		break;
		case GL_DEBUG_SOURCE_OTHER:				output += "Source: Other";				break;
		}

		output += "\n";

		switch (p_type)
		{
		case GL_DEBUG_TYPE_ERROR:               output += "Type: Error";				break;
		case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR: output += "Type: Deprecated Behaviour"; break;
		case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:  output += "Type: Undefined Behaviour";	break;
		case GL_DEBUG_TYPE_PORTABILITY:         output += "Type: Portability";			break;
		case GL_DEBUG_TYPE_PERFORMANCE:         output += "Type: Performance";			break;
		case GL_DEBUG_TYPE_MARKER:              output += "Type: Marker";				break;
		case GL_DEBUG_TYPE_PUSH_GROUP:          output += "Type: Push Group";			break;
		case GL_DEBUG_TYPE_POP_GROUP:           output += "Type: Pop Group";			break;
		case GL_DEBUG_TYPE_OTHER:               output += "Type: Other";				break;
		}

		output += "\n";

		switch (p_severity)
		{
		case GL_DEBUG_SEVERITY_HIGH:			output += "Severity: High";				BAREGL_LOG_ERROR(output);	break;
		case GL_DEBUG_SEVERITY_MEDIUM:			output += "Severity: Medium";			BAREGL_LOG_WARNING(output);	break;
		case GL_DEBUG_SEVERITY_LOW:				output += "Severity: Low";				BAREGL_LOG_INFO(output);	break;
		case GL_DEBUG_SEVERITY_NOTIFICATION:	output += "Severity: Notification";		BAREGL_LOG_INFO(output);	break;
		}
	}

	bool GetBool(uint32_t p_parameter)
	{
		GLboolean result;
		glGetBooleanv(p_parameter, &result);
		return static_cast<bool>(result);
	}

	bool GetBool(uint32_t p_parameter, uint32_t p_index)
	{
		GLboolean result;
		glGetBooleani_v(p_parameter, p_index, &result);
		return static_cast<bool>(result);
	}

	int GetInt(uint32_t p_parameter)
	{
		GLint result;
		glGetIntegerv(p_parameter, &result);
		return static_cast<int>(result);
	}

	int GetInt(uint32_t p_parameter, uint32_t p_index)
	{
		GLint result;
		glGetIntegeri_v(p_parameter, p_index, &result);
		return static_cast<int>(result);
	}

	float GetFloat(uint32_t p_parameter)
	{
		GLfloat result;
		glGetFloatv(p_parameter, &result);
		return static_cast<float>(result);
	}

	float GetFloat(uint32_t p_parameter, uint32_t p_index)
	{
		GLfloat result;
		glGetFloati_v(p_parameter, p_index, &result);
		return static_cast<float>(result);
	}

	double GetDouble(uint32_t p_parameter)
	{
		GLdouble result;
		glGetDoublev(p_parameter, &result);
		return static_cast<double>(result);
	}

	double GetDouble(uint32_t p_parameter, uint32_t p_index)
	{
		GLdouble result;
		glGetDoublei_v(p_parameter, p_index, &result);
		return static_cast<double>(result);
	}

	int64_t GetInt64(uint32_t p_parameter)
	{
		GLint64 result;
		glGetInteger64v(p_parameter, &result);
		return static_cast<int64_t>(result);
	}

	int64_t GetInt64(uint32_t p_parameter, uint32_t p_index)
	{
		GLint64 result;
		glGetInteger64i_v(p_parameter, p_index, &result);
		return static_cast<int64_t>(result);
	}

	std::string GetString(uint32_t p_parameter)
	{
		const GLubyte* result = glGetString(p_parameter);
		return result ? reinterpret_cast<const char*>(result) : std::string();
	}

	std::string GetString(uint32_t p_parameter, uint32_t p_index)
	{
		const GLubyte* result = glGetStringi(p_parameter, p_index);
		return result ? reinterpret_cast<const char*>(result) : std::string();
	}

	template<typename T>
	concept SupportedQueryType =
		std::same_as<T, int> || 
		std::same_as<T, int64_t> || 
		std::same_as<T, bool> || 
		std::same_as<T, float> || 
		std::same_as<T, double> ||
		std::same_as<T, std::string>;


	template<SupportedQueryType T>
	void GetValue(
		baregl::types::EGetParameter p_param,
		std::span<T> p_out
	);

	template<SupportedQueryType T>
	void GetValueIndexed(
		baregl::types::EGetParameter p_param,
		std::span<T> p_out,
		uint32_t p_index
	);

	template<>
	void GetValue<int>(
		baregl::types::EGetParameter p_param,
		std::span<int> p_out
	)
	{
		glGetIntegerv(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_out.data()
		);
	}

	template<>
	void GetValueIndexed<int>(
		baregl::types::EGetParameter p_param,
		std::span<int> p_out,
		uint32_t p_index
	)
	{
		glGetIntegeri_v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index,
			p_out.data()
		);
	}

	template<>
	void GetValue<int64_t>(
		baregl::types::EGetParameter p_param,
		std::span<int64_t> p_out
	)
	{
		glGetInteger64v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_out.data()
		);
	}

	template<>
	void GetValueIndexed<int64_t>(
		baregl::types::EGetParameter p_param,
		std::span<int64_t> p_out,
		uint32_t p_index
	)
	{
		glGetInteger64i_v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index,
			p_out.data()
		);
	}

	template<>
	void GetValue<bool>(
		baregl::types::EGetParameter p_param,
		std::span<bool> p_out
	)
	{
		std::vector<GLboolean> values(p_out.size());
		glGetBooleanv(
			baregl::utils::EnumToValue<GLenum>(p_param),
			values.data()
		);

		for (size_t i = 0; i < p_out.size(); ++i)
		{
			p_out[i] = values[i] != GL_FALSE;
		}
	}

	template<>
	void GetValueIndexed<bool>(
		baregl::types::EGetParameter p_param,
		std::span<bool> p_out,
		uint32_t p_index
	)
	{
		std::vector<GLboolean> values(p_out.size());
		glGetBooleani_v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index,
			values.data()
		);

		for (size_t i = 0; i < p_out.size(); ++i)
		{
			p_out[i] = values[i] != GL_FALSE;
		}
	}

	template<>
	void GetValue<float>(
		baregl::types::EGetParameter p_param,
		std::span<float> p_out
	)
	{
		glGetFloatv(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_out.data()
		);
	}

	template<>
	void GetValueIndexed<float>(
		baregl::types::EGetParameter p_param,
		std::span<float> p_out,
		uint32_t p_index
	)
	{
		glGetFloati_v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index,
			p_out.data()
		);
	}

	template<>
	void GetValue<double>(
		baregl::types::EGetParameter p_param,
		std::span<double> p_out
	)
	{
		glGetDoublev(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_out.data()
		);
	}

	template<>
	void GetValueIndexed<double>(
		baregl::types::EGetParameter p_param,
		std::span<double> p_out,
		uint32_t p_index
	)
	{
		glGetDoublei_v(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index,
			p_out.data()
		);
	}

	template<>
	void GetValue<std::string>(
		baregl::types::EGetParameter p_param,
		std::span<std::string> p_out
	)
	{
		p_out[0] = GetString(
			baregl::utils::EnumToValue<GLenum>(p_param)
		);
	}

	template<>
	void GetValueIndexed<std::string>(
		baregl::types::EGetParameter p_param,
		std::span<std::string> p_out,
		uint32_t p_index
	)
	{
		p_out[0] = GetString(
			baregl::utils::EnumToValue<GLenum>(p_param),
			p_index
		);
	}
}

namespace baregl
{
	Context::Context(const baregl::data::ContextDesc& p_desc)
	{
		BAREGL_ASSERT(g_contextCount == 0, "A context already exists. BareGL currently only supports a single context.");

		++g_contextCount;

		const int error = gladLoadGL();

		if (error == 0)
		{
			BAREGL_LOG_ERROR("GLAD failed to initialize");
			return;
		}

		BAREGL_LOG_INFO("OpenGL context initialized.");

		if (p_desc.debug)
		{
			glEnable(GL_DEBUG_OUTPUT);
			glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
			glDebugMessageCallback(GLDebugMessageCallback, nullptr);
		}

		// Seamless cubemap (always on)
		glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS);
		glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
	}

	Context::~Context()
	{
		BAREGL_ASSERT(g_contextCount > 0, "No context to destroy, did you modify g_contextCount manually?");

		--g_contextCount;
	}

	void Context::Clear(bool p_colorBuffer, bool p_depthBuffer, bool p_stencilBuffer)
	{
		GLbitfield clearMask = 0;
		if (p_colorBuffer) clearMask |= GL_COLOR_BUFFER_BIT;
		if (p_depthBuffer) clearMask |= GL_DEPTH_BUFFER_BIT;
		if (p_stencilBuffer) clearMask |= GL_STENCIL_BUFFER_BIT;

		if (clearMask != 0)
		{
			glClear(clearMask);
		}
	}

	void Context::DrawElements(types::EPrimitiveMode p_primitiveMode, uint32_t p_indexCount)
	{
		glDrawElements(utils::EnumToValue<GLenum>(p_primitiveMode), p_indexCount, GL_UNSIGNED_INT, nullptr);
	}

	void Context::DrawElementsInstanced(types::EPrimitiveMode p_primitiveMode, uint32_t p_indexCount, uint32_t p_instances)
	{
		glDrawElementsInstanced(utils::EnumToValue<GLenum>(p_primitiveMode), p_indexCount, GL_UNSIGNED_INT, nullptr, p_instances);
	}

	void Context::DrawArrays(types::EPrimitiveMode p_primitiveMode, uint32_t p_vertexCount)
	{
		glDrawArrays(utils::EnumToValue<GLenum>(p_primitiveMode), 0, p_vertexCount);
	}

	void Context::DrawArraysInstanced(types::EPrimitiveMode p_primitiveMode, uint32_t p_vertexCount, uint32_t p_instances)
	{
		glDrawArraysInstanced(utils::EnumToValue<GLenum>(p_primitiveMode), 0, p_vertexCount, p_instances);
	}

	void Context::DispatchCompute(uint32_t p_x, uint32_t p_y, uint32_t p_z) const
	{
		BAREGL_ASSERT(
			p_x > 0 && p_y > 0 && p_z > 0,
			"Dispatch work group count cannot be zero"
		);

		glDispatchCompute(p_x, p_y, p_z);
	}

	void Context::MemoryBarrier(types::EMemoryBarrierFlags p_barriers) const
	{
		glMemoryBarrier(
			utils::EnumToValue<GLbitfield>(p_barriers)
		);
	}

	void Context::SetClearColor(float p_red, float p_green, float p_blue, float p_alpha)
	{
		glClearColor(p_red, p_green, p_blue, p_alpha);
	}

	void Context::SetRasterizationLinesWidth(float p_width)
	{
		glLineWidth(p_width);
	}

	void Context::SetRasterizationMode(types::ERasterizationMode p_rasterizationMode)
	{
		glPolygonMode(GL_FRONT_AND_BACK, utils::EnumToValue<GLenum>(p_rasterizationMode));
	}

	void Context::SetCapability(types::ERenderingCapability p_capability, bool p_value)
	{
		(p_value ? glEnable : glDisable)(utils::EnumToValue<GLenum>(p_capability));
	}

	bool Context::GetCapability(types::ERenderingCapability p_capability)
	{
		return glIsEnabled(utils::EnumToValue<GLenum>(p_capability));
	}

	void Context::SetStencilAlgorithm(types::EComparaisonAlgorithm p_algorithm, int32_t p_reference, uint32_t p_mask)
	{
		glStencilFunc(utils::EnumToValue<GLenum>(p_algorithm), p_reference, p_mask);
	}

	void Context::SetDepthAlgorithm(types::EComparaisonAlgorithm p_algorithm)
	{
		glDepthFunc(utils::EnumToValue<GLenum>(p_algorithm));
	}

	void Context::SetStencilMask(uint32_t p_mask)
	{
		glStencilMask(p_mask);
	}

	void Context::SetStencilOperations(types::EOperation p_stencilFail, types::EOperation p_depthFail, types::EOperation p_bothPass)
	{
		glStencilOp(
			utils::EnumToValue<GLenum>(p_stencilFail),
			utils::EnumToValue<GLenum>(p_depthFail),
			utils::EnumToValue<GLenum>(p_bothPass)
		);
	}

	void Context::SetBlendingFunction(types::EBlendingFactor p_sourceFactor, types::EBlendingFactor p_destinationFactor)
	{
		glBlendFunc(
			utils::EnumToValue<GLenum>(p_sourceFactor),
			utils::EnumToValue<GLenum>(p_destinationFactor)
		);
	}

	void Context::SetBlendingEquation(types::EBlendingEquation p_equation)
	{
		glBlendEquation(utils::EnumToValue<GLenum>(p_equation));
	}

	void Context::SetCullFace(types::ECullFace p_cullFace)
	{
		glCullFace(utils::EnumToValue<GLenum>(p_cullFace));
	}

	void Context::SetDepthWriting(bool p_enable)
	{
		glDepthMask(p_enable);
	}

	void Context::SetColorWriting(bool p_enableRed, bool p_enableGreen, bool p_enableBlue, bool p_enableAlpha)
	{
		glColorMask(p_enableRed, p_enableGreen, p_enableBlue, p_enableAlpha);
	}

	void Context::SetViewport(uint32_t x, uint32_t y, uint32_t width, uint32_t height)
	{
		glViewport(x, y, width, height);
	}

	std::string Context::GetVendor()
	{
		return GetString(GL_VENDOR);
	}

	std::string Context::GetHardware()
	{
		return GetString(GL_RENDERER);
	}

	std::string Context::GetVersion()
	{
		return GetString(GL_VERSION);
	}

	std::string Context::GetShadingLanguageVersion()
	{
		return GetString(GL_SHADING_LANGUAGE_VERSION);
	}
		
	template<auto PName>
	data::QueryResultType<PName> Context::Get()
	{
		using R = data::QueryResult<PName>;
		using Elem = typename R::query_type;

		if constexpr (R::dynamic_count)
		{
			using CountQuery = data::QueryResult<R::dynamic_count_parameter>;
			using CountElem = typename CountQuery::query_type;
			std::array<CountElem, CountQuery::count> countRaw;
			GetValue<CountElem>(R::dynamic_count_parameter, countRaw);

			const auto elementCount = static_cast<size_t>(countRaw[0] > 0 ? countRaw[0] : 0);
			std::vector<Elem> raw(elementCount);
			GetValue<Elem>(PName, raw);

			if constexpr (std::same_as<typename R::type, std::vector<Elem>>)
			{
				return raw;
			}

			static_assert(std::same_as<typename R::type, std::vector<Elem>>, "Unsupported dynamic query result type");
		}
		else
		{
			constexpr size_t N = R::count;
			std::array<Elem, N> raw;
			GetValue<Elem>(PName, raw);

			if constexpr (std::same_as<typename R::type, Elem>)
				return raw[0];
			else if constexpr (std::same_as<typename R::type, std::array<Elem, N>>)
				return raw;
			else if constexpr (std::integral<typename R::type> && std::integral<Elem>)
				return static_cast<typename R::type>(raw[0]);
			else if constexpr (std::is_enum_v<typename R::type>)
				return utils::ValueToEnum<typename R::type>(static_cast<GLenum>(raw[0]));

			static_assert(
				std::same_as<typename R::type, Elem> ||
				std::same_as<typename R::type, std::array<Elem, N>> ||
				(std::integral<typename R::type> && std::integral<Elem>) ||
				std::is_enum_v<typename R::type>,
				"Unsupported query result type"
			);
		}
	}

	template<auto PName>
		requires (data::QueryResult<PName>::indexed)
	data::QueryResultType<PName> Context::Get(uint32_t p_index)
	{
		using R = data::QueryResult<PName>;
		using Elem = typename R::query_type;

		if constexpr (R::dynamic_count)
		{
			using CountQuery = data::QueryResult<R::dynamic_count_parameter>;
			using CountElem = typename CountQuery::query_type;
			using FetchQuery = data::QueryResult<R::dynamic_query_parameter>;
			using FetchElem = typename FetchQuery::query_type;

			std::array<CountElem, CountQuery::count> countRaw;
			GetValue<CountElem>(R::dynamic_count_parameter, countRaw);

			const auto elementCount = static_cast<size_t>(countRaw[0] > 0 ? countRaw[0] : 0);
			std::vector<FetchElem> raw(elementCount);
			GetValueIndexed<FetchElem>(R::dynamic_query_parameter, raw, p_index);

			if constexpr (std::same_as<typename R::type, std::vector<Elem>>)
			{
				return raw;
			}

			static_assert(std::same_as<typename R::type, std::vector<Elem>>, "Unsupported dynamic indexed query result type");
		}
		else
		{
			constexpr size_t N = R::count;
			std::array<Elem, N> raw;
			GetValueIndexed<Elem>(PName, raw, p_index);

			if constexpr (std::same_as<typename R::type, Elem>)
				return raw[0];
			else if constexpr (std::same_as<typename R::type, std::array<Elem, N>>)
				return raw;
			else if constexpr (std::integral<typename R::type> && std::integral<Elem>)
				return static_cast<typename R::type>(raw[0]);
			else if constexpr (std::is_enum_v<typename R::type>)
				return utils::ValueToEnum<typename R::type>(static_cast<GLenum>(raw[0]));

			static_assert(
				std::same_as<typename R::type, Elem> ||
				std::same_as<typename R::type, std::array<Elem, N>> ||
				(std::integral<typename R::type> && std::integral<Elem>) ||
				std::is_enum_v<typename R::type>,
				"Unsupported indexed query result type"
			);
		}
	}

#define INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(getType) \
	template data::QueryResultType<baregl::types::EGetParameter::getType> \
	Context::Get<baregl::types::EGetParameter::getType>()

#define INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(getType) \
	template data::QueryResultType<baregl::types::EGetParameter::getType> \
	Context::Get<baregl::types::EGetParameter::getType>(uint32_t)

#define INSTANTIATE_CUSTOM_QUERY_SPECIALIZATION(getType) \
	template<> \
	data::QueryResultType<baregl::types::EGetParameter::getType> \
	Context::Get<baregl::types::EGetParameter::getType>()

	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_NAME);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_LEVEL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_LAYERED);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_LAYER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_ACCESS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMAGE_BINDING_FORMAT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_START);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ACTIVE_TEXTURE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ALIASED_LINE_WIDTH_RANGE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ARRAY_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_COLOR);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_DST_ALPHA);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_DST_RGB);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_EQUATION_RGB);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_EQUATION_ALPHA);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_SRC_ALPHA);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(BLEND_SRC_RGB);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(COLOR_CLEAR_VALUE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(COLOR_LOGIC_OP);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(COLOR_WRITEMASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(COMPRESSED_TEXTURE_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_UNIFORM_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_TEXTURE_IMAGE_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_WORK_GROUP_INVOCATIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_WORK_GROUP_COUNT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMPUTE_WORK_GROUP_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DISPATCH_INDIRECT_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_DEBUG_GROUP_STACK_DEPTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEBUG_GROUP_STACK_DEPTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(CONTEXT_FLAGS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(EXTENSIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(RENDERER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADING_LANGUAGE_VERSION);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADING_LANGUAGE_VERSIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(NUM_SHADING_LANGUAGE_VERSIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VENDOR);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERSION);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(CULL_FACE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(CULL_FACE_MODE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(CURRENT_PROGRAM);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEPTH_CLEAR_VALUE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEPTH_FUNC);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEPTH_RANGE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEPTH_TEST);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DEPTH_WRITEMASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DITHER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DOUBLEBUFFER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER0);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER1);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER2);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER3);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER4);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER5);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER6);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER7);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER8);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER9);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER10);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER11);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER12);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER13);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER14);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_BUFFER15);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(DRAW_FRAMEBUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(READ_FRAMEBUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(ELEMENT_ARRAY_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(FRAGMENT_SHADER_DERIVATIVE_HINT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMPLEMENTATION_COLOR_READ_FORMAT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(IMPLEMENTATION_COLOR_READ_TYPE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(LINE_SMOOTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(LINE_SMOOTH_HINT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(LINE_WIDTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(LAYER_PROVOKING_VERTEX);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(LOGIC_OP_MODE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAJOR_VERSION);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_3D_TEXTURE_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_ARRAY_TEXTURE_LAYERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_CLIP_DISTANCES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_CULL_DISTANCES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_CLIP_AND_CULL_DISTANCES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COLOR_TEXTURE_SAMPLES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_TEXTURE_IMAGE_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_UNIFORM_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_CUBE_MAP_TEXTURE_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_DEPTH_TEXTURE_SAMPLES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_DRAW_BUFFERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_DUAL_SOURCE_DRAW_BUFFERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_ELEMENTS_INDICES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_ELEMENTS_VERTICES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_INPUT_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_UNIFORM_VECTORS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAGMENT_UNIFORM_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAMEBUFFER_WIDTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAMEBUFFER_HEIGHT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAMEBUFFER_LAYERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_FRAMEBUFFER_SAMPLES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_INPUT_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_OUTPUT_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_TEXTURE_IMAGE_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_UNIFORM_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_GEOMETRY_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_INTEGER_SAMPLES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MIN_MAP_BUFFER_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_LABEL_LENGTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_PROGRAM_TEXEL_OFFSET);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MIN_PROGRAM_TEXEL_OFFSET);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_RECTANGLE_TEXTURE_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_RENDERBUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_SAMPLE_MASK_WORDS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_SERVER_WAIT_TIMEOUT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_SHADER_STORAGE_BUFFER_BINDINGS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TESS_CONTROL_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TESS_EVALUATION_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TEXTURE_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TEXTURE_IMAGE_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TEXTURE_LOD_BIAS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_TEXTURE_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_UNIFORM_BUFFER_BINDINGS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_UNIFORM_BLOCK_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_UNIFORM_LOCATIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VARYING_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VARYING_VECTORS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VARYING_FLOATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATOMIC_COUNTER_BUFFERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATOMIC_COUNTERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATTRIBS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_SHADER_STORAGE_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_TEXTURE_IMAGE_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_UNIFORM_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_UNIFORM_VECTORS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_OUTPUT_COMPONENTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_UNIFORM_BLOCKS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VIEWPORT_DIMS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VIEWPORTS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MINOR_VERSION);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(NUM_COMPRESSED_TEXTURE_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(NUM_EXTENSIONS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(NUM_PROGRAM_BINARY_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(NUM_SHADER_BINARY_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_IMAGE_HEIGHT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_LSB_FIRST);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_ROW_LENGTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_SKIP_IMAGES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_SKIP_PIXELS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_SKIP_ROWS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PACK_SWAP_BYTES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PIXEL_PACK_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PIXEL_UNPACK_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POINT_FADE_THRESHOLD_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PRIMITIVE_RESTART_INDEX);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PROGRAM_BINARY_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_BINARY_FORMATS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PROGRAM_PIPELINE_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PROGRAM_POINT_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(PROVOKING_VERTEX);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POINT_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POINT_SIZE_GRANULARITY);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POINT_SIZE_RANGE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_FACTOR);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_UNITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_CLAMP);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_FILL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_LINE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_OFFSET_POINT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_SMOOTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(POLYGON_SMOOTH_HINT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(READ_BUFFER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(RENDERBUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLE_BUFFERS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLE_COVERAGE_VALUE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLE_COVERAGE_INVERT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLE_MASK_VALUE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SAMPLES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SCISSOR_BOX);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SCISSOR_TEST);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_COMPILER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_START);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SMOOTH_LINE_WIDTH_RANGE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SMOOTH_LINE_WIDTH_GRANULARITY);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_FAIL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_FUNC);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_PASS_DEPTH_FAIL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_PASS_DEPTH_PASS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_REF);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_VALUE_MASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_BACK_WRITEMASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_CLEAR_VALUE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_FAIL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_FUNC);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_PASS_DEPTH_FAIL);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_PASS_DEPTH_PASS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_REF);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_TEST);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_VALUE_MASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STENCIL_WRITEMASK);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(STEREO);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(SUBPIXEL_BITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_1D);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_1D_ARRAY);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_2D);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_2D_ARRAY);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_2D_MULTISAMPLE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_3D);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_BUFFER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_CUBE_MAP);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BINDING_RECTANGLE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_COMPRESSION_HINT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TEXTURE_BUFFER_OFFSET_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TIMESTAMP);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_START);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNIFORM_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNIFORM_BUFFER_OFFSET_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNIFORM_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNIFORM_BUFFER_START);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_ALIGNMENT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_IMAGE_HEIGHT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_LSB_FIRST);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_ROW_LENGTH);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_SKIP_IMAGES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_SKIP_PIXELS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_SKIP_ROWS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(UNPACK_SWAP_BYTES);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERTEX_ARRAY_BINDING);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERTEX_BINDING_DIVISOR);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERTEX_BINDING_OFFSET);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERTEX_BINDING_STRIDE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VERTEX_BINDING_BUFFER);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATTRIB_RELATIVE_OFFSET);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATTRIB_BINDINGS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_VERTEX_ATTRIB_STRIDE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VIEWPORT);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VIEWPORT_BOUNDS_RANGE);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VIEWPORT_INDEX_PROVOKING_VERTEX);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(VIEWPORT_SUBPIXEL_BITS);
	INSTANTIATE_DEFAULT_QUERY_SPECIALIZATION(MAX_ELEMENT_INDEX);

	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_NAME);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_LEVEL);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_LAYERED);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_LAYER);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_ACCESS);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(IMAGE_BINDING_FORMAT);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_START);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(ATOMIC_COUNTER_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(SHADING_LANGUAGE_VERSION);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(MAX_COMPUTE_WORK_GROUP_COUNT);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(MAX_COMPUTE_WORK_GROUP_SIZE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(SAMPLE_MASK_VALUE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_START);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(SHADER_STORAGE_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_START);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(TRANSFORM_FEEDBACK_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(UNIFORM_BUFFER_BINDING);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(UNIFORM_BUFFER_SIZE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(UNIFORM_BUFFER_START);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(VERTEX_BINDING_DIVISOR);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(VERTEX_BINDING_OFFSET);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(VERTEX_BINDING_STRIDE);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(VERTEX_BINDING_BUFFER);
	INSTANTIATE_DEFAULT_INDEXED_QUERY_SPECIALIZATION(VIEWPORT);
}
