/**
* @project: baregl
* @author: Adrien Givry
* @licence: MIT
*/

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <common/Boilerplate.h>

using namespace tests::common::boilerplate;
using namespace baregl;
using namespace baregl::types;
using enum baregl::types::EGetParameter;

TEST_CASE( "Context can be created", "[context]" ) {
	RunInWindow([](GLFWwindow* p_window) {
		Context context;
	});
}

TEST_CASE( "Context can be recreated", "[context]" ) {
	RunInWindow([](GLFWwindow* p_window) {
		auto context = std::make_unique<Context>();
		context.reset();
		context = std::make_unique<Context>();
	});
}

#define GET(query, ...) p_context.Get<query>(__VA_ARGS__)
#define GET_WORKS(query, ...) (GET(query, __VA_ARGS__), true)

TEST_CASE( "Context::Get return the expected values", "[context]" ) {
	RunInContext([](GLFWwindow* p_window, Context& p_context) {
		Buffer vbo;
		Buffer ibo;
		Buffer ssbo;
		Buffer ubo;
		Framebuffer fbo;
		VertexArray vao;
		std::array<Buffer, 4> ssbos;
		REQUIRE( GET(PATCH_VERTICES) == 3 );
		REQUIRE( GET(PATCH_DEFAULT_OUTER_LEVEL) == std::to_array({1.0f,1.0f,1.0f,1.0f}) );
		REQUIRE( GET(PATCH_DEFAULT_INNER_LEVEL) == std::to_array({1.0f,1.0f}) );
		REQUIRE( GET(ELEMENT_ARRAY_BUFFER_BINDING) == 0 );
		ibo.Bind(EBufferType::INDEX);
		REQUIRE( GET(ELEMENT_ARRAY_BUFFER_BINDING) == ibo.GetID() );
		ibo.Unbind();
		REQUIRE( GET(VERTEX_BINDING_OFFSET, 0) == 0 );
		REQUIRE( GET(VERTEX_BINDING_STRIDE, 0) == 16 );
		REQUIRE( GET(VERTEX_BINDING_DIVISOR, 0) == 0 ); // FIXME: Spec says initial value should be 16
		REQUIRE( GET(VERTEX_BINDING_BUFFER, 0) == 0 ); // FIXME: Spec says initial value should be 16
		REQUIRE( GET(ARRAY_BUFFER_BINDING) == 0 );
		vbo.Bind(EBufferType::VERTEX);
		REQUIRE( GET(ARRAY_BUFFER_BINDING) == vbo.GetID() );
		vbo.Unbind();
		REQUIRE( GET(DRAW_INDIRECT_BUFFER_BINDING) == 0 );
		REQUIRE( GET(VERTEX_ARRAY_BINDING) == 0 );
		vao.Bind();
		REQUIRE( GET(VERTEX_ARRAY_BINDING) == vao.GetID() );
		vao.Unbind();
		REQUIRE( GET(PRIMITIVE_RESTART) == false );
		REQUIRE( GET(PRIMITIVE_RESTART_FIXED_INDEX) == false );
		REQUIRE( GET(PRIMITIVE_RESTART_INDEX) == 0 );
		p_context.SetViewport(0, 1, 2, 3);
		REQUIRE( GET(VIEWPORT) == std::to_array({0,1,2,3}) );
		REQUIRE( GET_WORKS(VIEWPORT, 0) );
		// TODO: Add support for indexed viewports
		// REQUIRE( GET(VIEWPORT, 1) == std::to_array({0,1,2,3}) );
		REQUIRE( GET(DEPTH_RANGE) == std::to_array({0.0, 1.0}) );
		REQUIRE( GET(CLIP_DISTANCE0) == false );
		REQUIRE( GET(CLIP_DISTANCE1) == false );
		REQUIRE( GET(CLIP_DISTANCE2) == false );
		REQUIRE( GET(CLIP_DISTANCE3) == false );
		REQUIRE( GET(CLIP_DISTANCE4) == false );
		REQUIRE( GET(CLIP_DISTANCE5) == false );
		REQUIRE( GET(CLIP_DISTANCE6) == false );
		REQUIRE( GET(CLIP_DISTANCE7) == false );
		REQUIRE( GET_WORKS(CLIP_ORIGIN) );
		REQUIRE( GET_WORKS(CLIP_DEPTH_MODE) );
		REQUIRE( GET(DEPTH_CLAMP) == false );
		REQUIRE( GET(TRANSFORM_FEEDBACK_BINDING) == 0 );
		REQUIRE( GET_WORKS(CLAMP_READ_COLOR) );
		REQUIRE( GET(PROVOKING_VERTEX) == EProvokingVertexConvention::LAST_VERTEX_CONVENTION );
		REQUIRE( GET(RASTERIZER_DISCARD) == false );
		REQUIRE( GET(POINT_SIZE) == 1.0f );
		REQUIRE( GET(POINT_FADE_THRESHOLD_SIZE) == 1.0f );
		REQUIRE( GET_WORKS(POINT_SPRITE_COORD_ORIGIN) );
		REQUIRE( GET(LINE_WIDTH) == 1.0f);
		p_context.SetRasterizationLinesWidth(2.0f);
		REQUIRE( GET(LINE_WIDTH) == 2.0f);
		REQUIRE( GET(LINE_SMOOTH) == false );
		p_context.SetCapability(ERenderingCapability::LINE_SMOOTH, true);
		REQUIRE( GET(LINE_SMOOTH) == true );
		REQUIRE( GET(CULL_FACE) == false );
		p_context.SetCapability(ERenderingCapability::CULL_FACE, true);
		REQUIRE( GET(CULL_FACE) == true );
		REQUIRE( GET(CULL_FACE_MODE) == ECullFace::BACK );
		p_context.SetCullFace(ECullFace::FRONT_AND_BACK);
		REQUIRE( GET(CULL_FACE_MODE) == ECullFace::FRONT_AND_BACK );
		REQUIRE( GET_WORKS(FRONT_FACE) );
		REQUIRE( GET(POLYGON_SMOOTH) == false ); // TODO: How do we enable that??
		REQUIRE( GET_WORKS(POLYGON_MODE) );
		REQUIRE( GET(POLYGON_OFFSET_FACTOR) == 0.0f );
		REQUIRE( GET(POLYGON_OFFSET_UNITS) == 0.0f );
		REQUIRE( GET(POLYGON_OFFSET_POINT) == false );
		REQUIRE( GET(POLYGON_OFFSET_LINE) == false );
		REQUIRE( GET(POLYGON_OFFSET_FILL) == false );
		REQUIRE( GET(MULTISAMPLE) == true );
		REQUIRE( GET(SAMPLE_ALPHA_TO_COVERAGE) == false );
		REQUIRE( GET(SAMPLE_ALPHA_TO_ONE) == false );
		REQUIRE( GET(SAMPLE_COVERAGE) == false );
		REQUIRE( GET(SAMPLE_COVERAGE_VALUE) == 1.0f );
		REQUIRE( GET(SAMPLE_COVERAGE_INVERT) == false );
		REQUIRE( GET(SAMPLE_SHADING) == false );
		REQUIRE( GET(MIN_SAMPLE_SHADING_VALUE) == 0.0f );
		REQUIRE( GET(SAMPLE_MASK) == false );
		REQUIRE( GET(SAMPLE_MASK_VALUE, 0) == ~0 );
		REQUIRE( GET(TEXTURE_BINDING_1D) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_2D) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_3D) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_1D_ARRAY) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_2D_ARRAY) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_CUBE_MAP_ARRAY) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_RECTANGLE) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_BUFFER) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_CUBE_MAP) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_2D_MULTISAMPLE) == 0 );
		REQUIRE( GET(TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY) == 0 );
		REQUIRE( GET(SAMPLER_BINDING) == 0 );

		REQUIRE( GET(ACTIVE_TEXTURE) == ETextureUnit::TEXTURE0 );
		REQUIRE( GET(SCISSOR_TEST) == false );
		p_context.SetCapability(ERenderingCapability::SCISSOR_TEST, true);
		REQUIRE( GET(SCISSOR_TEST) == true );
		REQUIRE( GET(SCISSOR_BOX)[0] == 0 );
		REQUIRE( GET(SCISSOR_BOX)[1] == 0 );
		REQUIRE( GET(SCISSOR_BOX)[2] == 256 ); // Window width
		REQUIRE( GET(SCISSOR_BOX)[3] == 256 ); // Window height
		REQUIRE( GET(STENCIL_TEST) == false );
		REQUIRE( GET(STENCIL_FUNC) == EComparaisonAlgorithm::ALWAYS );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( GET(STENCIL_VALUE_MASK) == 1 );
		REQUIRE( GET(STENCIL_REF) == 0 );
		REQUIRE( GET(STENCIL_FAIL) == EOperation::KEEP );
		REQUIRE( GET(STENCIL_PASS_DEPTH_FAIL) == EOperation::KEEP );
		REQUIRE( GET(STENCIL_PASS_DEPTH_PASS) == EOperation::KEEP );
		REQUIRE( GET(STENCIL_BACK_FUNC) == EComparaisonAlgorithm::ALWAYS );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( GET(STENCIL_BACK_VALUE_MASK) == 1 );
		REQUIRE( GET(STENCIL_BACK_REF) == 0 );
		REQUIRE( GET(STENCIL_BACK_FAIL) == EOperation::KEEP );
		REQUIRE( GET(STENCIL_BACK_PASS_DEPTH_FAIL) == EOperation::KEEP );
		REQUIRE( GET(STENCIL_BACK_PASS_DEPTH_PASS) == EOperation::KEEP );
		REQUIRE( GET(DEPTH_TEST) == false );
		p_context.SetCapability(ERenderingCapability::DEPTH_TEST, true);
		REQUIRE( GET(DEPTH_TEST) == true );
		REQUIRE( GET(DEPTH_FUNC) == EComparaisonAlgorithm::LESS );
		p_context.SetCapability(ERenderingCapability::BLEND, true);
		REQUIRE( GET(BLEND) == true );
		p_context.SetBlendingFunction(EBlendingFactor::CONSTANT_ALPHA, EBlendingFactor::CONSTANT_ALPHA);
		REQUIRE( GET(BLEND_SRC_RGB) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( GET(BLEND_SRC_ALPHA) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( GET(BLEND_DST_RGB) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( GET(BLEND_DST_ALPHA) == EBlendingFactor::CONSTANT_ALPHA );
		p_context.SetBlendingEquation(EBlendingEquation::FUNC_REVERSE_SUBTRACT);
		REQUIRE( GET(BLEND_EQUATION_RGB) == EBlendingEquation::FUNC_REVERSE_SUBTRACT );
		REQUIRE( GET(BLEND_EQUATION_ALPHA) == EBlendingEquation::FUNC_REVERSE_SUBTRACT );
		REQUIRE( GET(BLEND_COLOR) == std::to_array({0.0f,0.0f,0.0f,0.0f}) );
		REQUIRE( GET(FRAMEBUFFER_SRGB) == false );
		REQUIRE( GET(DITHER) == true );
		p_context.SetCapability(ERenderingCapability::DITHER, false);
		REQUIRE( GET(DITHER) == false );
		REQUIRE( GET(COLOR_LOGIC_OP) == false );
		REQUIRE( GET(LOGIC_OP_MODE) == ELogicOperation::COPY );
		REQUIRE( GET(COLOR_WRITEMASK) == std::to_array({true,true,true,true}) );
		p_context.SetColorWriting(true, false, true, false);
		REQUIRE( GET(COLOR_WRITEMASK) == std::to_array({true,false,true,false}) );
		REQUIRE( GET(DEPTH_WRITEMASK) == true );
		p_context.SetDepthWriting(false);
		REQUIRE( GET(DEPTH_WRITEMASK) == false );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( GET(STENCIL_WRITEMASK) == 1 );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( GET(STENCIL_BACK_WRITEMASK) == 1 );
		REQUIRE( GET(COLOR_CLEAR_VALUE) == std::to_array({0.0f,0.0f,0.0f,0.0f}));
		p_context.SetClearColor(0.1f, 0.2f, 0.3f, 0.4f);
		REQUIRE( GET(COLOR_CLEAR_VALUE) == std::to_array({0.1f,0.2f,0.3f,0.4f}));
		REQUIRE( GET(DEPTH_CLEAR_VALUE) == 1.0 );
		REQUIRE( GET(STENCIL_CLEAR_VALUE) == 0 );
		REQUIRE( GET(DRAW_FRAMEBUFFER_BINDING) == 0 );
		fbo.Bind();
		REQUIRE( GET(DRAW_FRAMEBUFFER_BINDING) == fbo.GetID() );
		REQUIRE( GET(READ_FRAMEBUFFER_BINDING) == fbo.GetID() );
		fbo.Unbind();
		REQUIRE( GET(DRAW_BUFFER) == EDrawBuffer::BACK );
		REQUIRE( GET(DRAW_BUFFER0) == EDrawBuffer::BACK );
		REQUIRE( GET(DRAW_BUFFER1) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER2) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER3) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER4) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER5) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER6) == EDrawBuffer::NONE );
		REQUIRE( GET(DRAW_BUFFER7) == EDrawBuffer::NONE );
		const auto maxBuffers = GET(MAX_DRAW_BUFFERS);
		REQUIRE( (maxBuffers < 9 || GET(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 10 || GET(DRAW_BUFFER9) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 11 || GET(DRAW_BUFFER10) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 12 || GET(DRAW_BUFFER11) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 13 || GET(DRAW_BUFFER12) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 14 || GET(DRAW_BUFFER13) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 15 || GET(DRAW_BUFFER14) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 16 || GET(DRAW_BUFFER15) == EDrawBuffer::NONE) );
		REQUIRE( GET(READ_BUFFER) == EDrawBuffer::BACK );
		fbo.Bind();
		REQUIRE( GET(READ_BUFFER) == EDrawBuffer::COLOR_ATTACHMENT0 );
		fbo.Unbind();
		REQUIRE( GET(RENDERBUFFER_BINDING) == 0 );
		REQUIRE( GET(UNPACK_SWAP_BYTES) == false );
		REQUIRE( GET(UNPACK_LSB_FIRST) == false );
		REQUIRE( GET(UNPACK_IMAGE_HEIGHT) == 0 );
		REQUIRE( GET(UNPACK_SKIP_IMAGES) == 0 );
		REQUIRE( GET(UNPACK_ROW_LENGTH) == 0 );
		REQUIRE( GET(UNPACK_SKIP_ROWS) == 0 );
		REQUIRE( GET(UNPACK_SKIP_PIXELS) == 0 );
		REQUIRE( GET(UNPACK_ALIGNMENT) == 4 );
		REQUIRE( GET(UNPACK_COMPRESSED_BLOCK_WIDTH) == 0 );
		REQUIRE( GET(UNPACK_COMPRESSED_BLOCK_HEIGHT) == 0 );
		REQUIRE( GET(UNPACK_COMPRESSED_BLOCK_DEPTH) == 0 );
		REQUIRE( GET(UNPACK_COMPRESSED_BLOCK_SIZE) == 0 );
		REQUIRE( GET(PIXEL_UNPACK_BUFFER_BINDING) == 0 );
		REQUIRE( GET(PACK_SWAP_BYTES) == false );
		REQUIRE( GET(PACK_LSB_FIRST) == false );
		REQUIRE( GET(PACK_IMAGE_HEIGHT) == 0 );
		REQUIRE( GET(PACK_SKIP_IMAGES) == 0 );
		REQUIRE( GET(PACK_ROW_LENGTH) == 0 );
		REQUIRE( GET(PACK_SKIP_ROWS) == 0 );
		REQUIRE( GET(PACK_SKIP_PIXELS) == 0 );
		REQUIRE( GET(PACK_ALIGNMENT) == 4 );
		REQUIRE( GET(PACK_COMPRESSED_BLOCK_WIDTH) == 0 );
		REQUIRE( GET(PACK_COMPRESSED_BLOCK_HEIGHT) == 0);
		REQUIRE( GET(PACK_COMPRESSED_BLOCK_DEPTH) == 0 );
		REQUIRE( GET(PACK_COMPRESSED_BLOCK_SIZE) == 0 );
		REQUIRE( GET(PIXEL_PACK_BUFFER_BINDING) == 0 );
		REQUIRE( GET(CURRENT_PROGRAM) == 0 );
		REQUIRE( GET(PROGRAM_PIPELINE_BINDING) == 0 );
		REQUIRE( GET(PROGRAM_POINT_SIZE) == false );
		REQUIRE( GET(IMAGE_BINDING_NAME, 1) == 0 );
		REQUIRE( GET(IMAGE_BINDING_LEVEL, 1) == 0 );
		REQUIRE( GET(IMAGE_BINDING_LAYERED, 1) == false );
		REQUIRE( GET(IMAGE_BINDING_LAYER, 1) == 0 );
		REQUIRE( GET(IMAGE_BINDING_ACCESS, 1) == EImageAccessSpecifier::READ_ONLY );
		REQUIRE( GET(IMAGE_BINDING_FORMAT, 1) == EInternalFormat::R8 );
		REQUIRE( GET(ATOMIC_COUNTER_BUFFER_BINDING, 0) == 0 );
		REQUIRE( GET(ATOMIC_COUNTER_BUFFER_BINDING) == 0 );
		REQUIRE( GET(ATOMIC_COUNTER_BUFFER_START, 0) == 0 );
		REQUIRE( GET(ATOMIC_COUNTER_BUFFER_SIZE, 0) == 0 );
		REQUIRE( GET(SHADER_STORAGE_BUFFER_BINDING) == 0 );
		ssbo.Bind(EBufferType::SHADER_STORAGE);
		REQUIRE( GET(SHADER_STORAGE_BUFFER_BINDING) == ssbo.GetID() );
		ssbo.Unbind();
		for (size_t i = 0; i < 4; ++i)
		{
			ssbos[i].Bind(EBufferType::SHADER_STORAGE, i);
			REQUIRE( GET(SHADER_STORAGE_BUFFER_BINDING, i) == ssbos[i].GetID() );
			ssbos[i].Unbind();
		}
		// FIXME: Spec says default value is 0, yet I get 140733763744992
		// REQUIRE( GET(SHADER_STORAGE_BUFFER_START) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140733909164800
		// REQUIRE( GET(SHADER_STORAGE_BUFFER_SIZE) == 0 );
		REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_BINDING) == 0 );
		REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_BINDING, 0) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140723345732688
		// REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_START) == 0 );
		REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_START, 0) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140736376922736
		// REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_SIZE) == 0 );
		REQUIRE( GET(TRANSFORM_FEEDBACK_BUFFER_SIZE, 0) == 0 );
		REQUIRE( GET(TRANSFORM_FEEDBACK_PAUSED) == false );
		REQUIRE( GET(TRANSFORM_FEEDBACK_ACTIVE) == false );
		REQUIRE( GET(UNIFORM_BUFFER_BINDING) == 0 );
		ubo.Bind(types::EBufferType::UNIFORM);
		REQUIRE( GET(UNIFORM_BUFFER_BINDING) == ubo.GetID() );
		ubo.Unbind();
		REQUIRE( GET(UNIFORM_BUFFER_BINDING, 4) == 0 );
		ubo.Bind(types::EBufferType::UNIFORM, 4);
		REQUIRE( GET(UNIFORM_BUFFER_BINDING, 4) == ubo.GetID() );
		REQUIRE( GET(UNIFORM_BUFFER_START, 0) == 0 );
		REQUIRE( GET(UNIFORM_BUFFER_SIZE, 0) == 0 );
		REQUIRE( GET(LINE_SMOOTH_HINT) == EHint::DONT_CARE );
		REQUIRE( GET(POLYGON_SMOOTH_HINT) == EHint::DONT_CARE );
		REQUIRE( GET(TEXTURE_COMPRESSION_HINT) == EHint::DONT_CARE );
		REQUIRE( GET(FRAGMENT_SHADER_DERIVATIVE_HINT) == EHint::DONT_CARE );

		REQUIRE( GET(DISPATCH_INDIRECT_BUFFER_BINDING) == 0 );
		REQUIRE( GET_WORKS(CONTEXT_RELEASE_BEHAVIOR) );
		REQUIRE( GET(MAX_CLIP_DISTANCES) >= 8 );
		REQUIRE( GET(MAX_CULL_DISTANCES) >= 8 );
		REQUIRE( GET(MAX_COMBINED_CLIP_AND_CULL_DISTANCES) >= 8 );
		REQUIRE( GET(SUBPIXEL_BITS) >= 4 );
		REQUIRE( GET(MAX_ELEMENT_INDEX) >= (1LL << 32) - 1 );
		REQUIRE( GET_WORKS(PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED) );
		REQUIRE( GET(MAX_3D_TEXTURE_SIZE) >= 2048 );
		REQUIRE( GET(MAX_TEXTURE_SIZE) >= 16384 );
		REQUIRE( GET(MAX_ARRAY_TEXTURE_LAYERS) >= 2048 );
		REQUIRE( GET(MAX_TEXTURE_LOD_BIAS) >= 2.0f );
		REQUIRE( GET(MAX_CUBE_MAP_TEXTURE_SIZE) >= 16384 );
		REQUIRE( GET(MAX_RENDERBUFFER_SIZE) >= 16384 );
		REQUIRE( GET(MAX_VIEWPORT_DIMS)[0] >= GET(MAX_RENDERBUFFER_SIZE) );
		REQUIRE( GET(MAX_VIEWPORT_DIMS)[1] >= GET(MAX_RENDERBUFFER_SIZE) );
		REQUIRE( GET(MAX_VIEWPORTS) >= 16 );
		REQUIRE( GET(VIEWPORT_SUBPIXEL_BITS) >= 0 );
		REQUIRE( GET(VIEWPORT_BOUNDS_RANGE)[0] <= -32768.0f );
		REQUIRE( GET(VIEWPORT_BOUNDS_RANGE)[1] >= 32767.0f );
		// FIXME: Value not found in mapping
		// REQUIRE( GET_WORKS(LAYER_PROVOKING_VERTEX) );
		REQUIRE( GET_WORKS(VIEWPORT_INDEX_PROVOKING_VERTEX) );
		REQUIRE( GET(POINT_SIZE_RANGE)[0] <= 1.0f );
		REQUIRE( GET(POINT_SIZE_RANGE)[1] >= 1.0f );
		REQUIRE( GET_WORKS(POINT_SIZE_GRANULARITY) );
		REQUIRE( GET(ALIASED_LINE_WIDTH_RANGE)[0] <= 1.0f );
		REQUIRE( GET(ALIASED_LINE_WIDTH_RANGE)[1] >= 1.0f );
		REQUIRE( GET(SMOOTH_LINE_WIDTH_RANGE)[0] <= 1.0f );
		REQUIRE( GET(SMOOTH_LINE_WIDTH_RANGE)[1] >= 1.0f );
		REQUIRE( GET_WORKS(SMOOTH_LINE_WIDTH_GRANULARITY) );
		REQUIRE( GET_WORKS(MAX_ELEMENTS_INDICES) );
		REQUIRE( GET_WORKS(MAX_ELEMENTS_VERTICES) );	
		REQUIRE( GET(MAX_VERTEX_ATTRIB_RELATIVE_OFFSET) >= 2047 );
		REQUIRE( GET(MAX_VERTEX_ATTRIB_BINDINGS) >= 16 );
		REQUIRE( GET(MAX_VERTEX_ATTRIB_STRIDE) >= 2048 );
		REQUIRE( GET(NUM_COMPRESSED_TEXTURE_FORMATS) >= 12 ); // Should be 18 according to the specs, but some implementations aren't fully compliant (which is the case for baregl's CI runner)
		REQUIRE( GET(COMPRESSED_TEXTURE_FORMATS).size() == GET(NUM_COMPRESSED_TEXTURE_FORMATS) );
		REQUIRE( GET(MAX_TEXTURE_BUFFER_SIZE) >= 65536 );
		REQUIRE( GET(MAX_RECTANGLE_TEXTURE_SIZE) >= 16384 );
		REQUIRE( GET(NUM_PROGRAM_BINARY_FORMATS) >= 0 );
		REQUIRE( GET(PROGRAM_BINARY_FORMATS).size() == GET(NUM_PROGRAM_BINARY_FORMATS) );
		REQUIRE( GET(NUM_SHADER_BINARY_FORMATS) >= 0 );
		REQUIRE( GET(SHADER_BINARY_FORMATS).size() == GET(NUM_SHADER_BINARY_FORMATS) );
		REQUIRE( GET(SHADER_COMPILER) == true );
		REQUIRE( GET(MIN_MAP_BUFFER_ALIGNMENT) >= 64 ); // Must be power of 2
		REQUIRE( GET(TEXTURE_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( GET(MAJOR_VERSION) == 4 );
		REQUIRE( GET(MINOR_VERSION) == 5 );
		REQUIRE( GET(CONTEXT_FLAGS) == EContextFlags::DEBUG_BIT );
		REQUIRE( GET_WORKS(CONTEXT_PROFILE_MASK) );
		REQUIRE( GET(EXTENSIONS).size() == GET(NUM_EXTENSIONS) );
		REQUIRE( GET_WORKS(NUM_EXTENSIONS) );
		REQUIRE( GET_WORKS(RENDERER) );
		REQUIRE( GET_WORKS(SHADING_LANGUAGE_VERSION) );
		// FIXME: Retrieval doesn't seem to work properly (dynamic with different query param issue?)
		// REQUIRE( GET(SHADING_LANGUAGE_VERSIONS).size() == GET(NUM_SHADING_LANGUAGE_VERSIONS) );
		// for (auto& version : GET(SHADING_LANGUAGE_VERSIONS))
		// {
		// 	printf("Version: %s\n", version.c_str());
		// }
		// REQUIRE_FALSE(true);
		REQUIRE( GET(NUM_SHADING_LANGUAGE_VERSIONS) >= 3 );
		REQUIRE( GET_WORKS(VENDOR) );
		REQUIRE( GET_WORKS(VERSION) );
		REQUIRE( GET(MAX_VERTEX_ATTRIBS) >= 16 );
		REQUIRE( GET(MAX_VERTEX_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_VERTEX_UNIFORM_VECTORS) >= 256 );
		REQUIRE( GET(MAX_VERTEX_UNIFORM_VECTORS) == GET(MAX_VERTEX_UNIFORM_COMPONENTS) / 4 );
		REQUIRE( GET(MAX_VERTEX_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( GET(MAX_VERTEX_OUTPUT_COMPONENTS) >= 64 );
		REQUIRE( GET(MAX_VERTEX_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MAX_VERTEX_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( GET(MAX_VERTEX_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( GET(MAX_VERTEX_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( GET(MAX_TESS_GEN_LEVEL) >= 64 );
		REQUIRE( GET(MAX_PATCH_VERTICES) >= 32 );
		REQUIRE( GET(MAX_TESS_CONTROL_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MAX_TESS_CONTROL_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( GET(MAX_TESS_PATCH_COMPONENTS) >= 120 );
		REQUIRE( GET(MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS) >= 4096 );
		REQUIRE( GET(MAX_TESS_CONTROL_INPUT_COMPONENTS) >= 128 );
		REQUIRE( GET_WORKS(MAX_TESS_CONTROL_UNIFORM_BLOCKS) );
		REQUIRE( GET(MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( GET(MAX_TESS_CONTROL_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( GET(MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( GET(MAX_TESS_EVALUATION_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MAX_TESS_EVALUATION_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( GET(MAX_TESS_EVALUATION_INPUT_COMPONENTS) >= 128 );
		REQUIRE( GET(MAX_TESS_EVALUATION_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( GET(MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( GET(MAX_TESS_EVALUATION_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( GET(MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( GET(MAX_GEOMETRY_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_GEOMETRY_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( GET(MAX_GEOMETRY_INPUT_COMPONENTS) >= 64 );
		REQUIRE( GET(MAX_GEOMETRY_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( GET(MAX_GEOMETRY_OUTPUT_VERTICES) >= 256 );
		REQUIRE( GET(MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_GEOMETRY_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MAX_GEOMETRY_SHADER_INVOCATIONS) >= 32 );
		REQUIRE( GET(MAX_VERTEX_STREAMS) >= 4 );
		REQUIRE( GET(MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( GET(MAX_GEOMETRY_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( GET(MAX_GEOMETRY_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( GET(MAX_FRAGMENT_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_FRAGMENT_UNIFORM_VECTORS) >= GET(MAX_FRAGMENT_UNIFORM_COMPONENTS) / 4 );
		REQUIRE( GET(MAX_FRAGMENT_UNIFORM_VECTORS) >= 256 );
		REQUIRE( GET(MAX_FRAGMENT_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( GET(MAX_FRAGMENT_INPUT_COMPONENTS) >= 128 );
		REQUIRE( GET(MAX_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MIN_PROGRAM_TEXTURE_GATHER_OFFSET) <= -8 );
		REQUIRE( GET(MAX_PROGRAM_TEXTURE_GATHER_OFFSET) >= 7 );
		REQUIRE( GET(MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS) >= 1 );
		REQUIRE( GET(MAX_FRAGMENT_ATOMIC_COUNTERS) >= 8 );
		REQUIRE( GET(MAX_FRAGMENT_SHADER_STORAGE_BLOCKS) >= 8 );

		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_COUNT, 0) >= 65535 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_COUNT, 1) >= 65535 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_COUNT, 2) >= 65535 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_SIZE, 0) >= 1024 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_SIZE, 1) >= 1024 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_SIZE, 2) >= 64 );
		REQUIRE( GET(MAX_COMPUTE_WORK_GROUP_INVOCATIONS) >= 1024 );
		REQUIRE( GET(MAX_COMPUTE_UNIFORM_BLOCKS) >= 11 ); // Spec says 14 is minimum, but some driver implementations have lower values
		REQUIRE( GET(MAX_COMPUTE_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( GET(MAX_COMPUTE_ATOMIC_COUNTERS) >= 8 );
		REQUIRE( GET(MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS) >= 8 );
		REQUIRE( GET(MAX_COMPUTE_SHARED_MEMORY_SIZE) >= 32768 );
		REQUIRE( GET(MAX_COMPUTE_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( GET(MAX_COMPUTE_IMAGE_UNIFORMS) >= 8 );
		REQUIRE( GET(MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS) >= 0 ); // Spec says "*"?
		REQUIRE( GET(MAX_COMPUTE_SHADER_STORAGE_BLOCKS) >= 8 );
		REQUIRE( GET(MIN_PROGRAM_TEXEL_OFFSET) <= -8 );
		REQUIRE( GET(MAX_PROGRAM_TEXEL_OFFSET) >= 7 );
		REQUIRE( GET(MAX_UNIFORM_BUFFER_BINDINGS) >= 36 );
		REQUIRE( GET(MAX_UNIFORM_BLOCK_SIZE) >= 16384 );
		ubo.Unbind();
		REQUIRE( GET(UNIFORM_BUFFER_OFFSET_ALIGNMENT) >= 1 );
		REQUIRE( GET(UNIFORM_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( GET(MAX_COMBINED_UNIFORM_BLOCKS) >= 70 );
		REQUIRE( GET(MAX_VARYING_COMPONENTS) >= 60 );
		REQUIRE( GET(MAX_VARYING_VECTORS) >= 15 );
		REQUIRE( GET(MAX_VARYING_VECTORS) == GET(MAX_VARYING_COMPONENTS) / 4);
		REQUIRE( GET(MAX_VARYING_FLOATS) >= 32 );
		REQUIRE( GET(MAX_COMBINED_TEXTURE_IMAGE_UNITS) >= 48 );
		REQUIRE( GET(MAX_SUBROUTINES) >= 256 );
		REQUIRE( GET(MAX_SUBROUTINE_UNIFORM_LOCATIONS) >= 1024 );
		REQUIRE( GET(MAX_UNIFORM_LOCATIONS) >= 1024 );
		REQUIRE( GET(MAX_ATOMIC_COUNTER_BUFFER_BINDINGS) >= 1 );
		REQUIRE( GET(MAX_ATOMIC_COUNTER_BUFFER_SIZE) >= 32 );
		REQUIRE( GET(MAX_COMBINED_ATOMIC_COUNTER_BUFFERS) >= 1 );
		REQUIRE( GET(MAX_COMBINED_ATOMIC_COUNTERS) >= 8 );
		REQUIRE( GET(MAX_SHADER_STORAGE_BUFFER_BINDINGS) >= 8 );
		REQUIRE( GET(MAX_SHADER_STORAGE_BLOCK_SIZE) >= 1 << 27 );

		REQUIRE( GET(MAX_COMBINED_SHADER_STORAGE_BLOCKS) >= 8 );
		REQUIRE( GET(SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT) >= 1 );
		REQUIRE( GET(SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( GET(MAX_IMAGE_UNITS) >= 8 );
		REQUIRE( GET(MAX_COMBINED_SHADER_OUTPUT_RESOURCES) >= 8 );
		REQUIRE( GET(MAX_IMAGE_SAMPLES) >= 0 );
		REQUIRE( GET(MAX_VERTEX_IMAGE_UNIFORMS) >= 0 );
		REQUIRE( GET(MAX_TESS_CONTROL_IMAGE_UNIFORMS) >= 0 );
		REQUIRE( GET(MAX_TESS_EVALUATION_IMAGE_UNIFORMS) >= 0 );
		REQUIRE( GET(MAX_GEOMETRY_IMAGE_UNIFORMS) >= 0 );
		REQUIRE( GET(MAX_FRAGMENT_IMAGE_UNIFORMS) >= 8 );
		REQUIRE( GET(MAX_COMBINED_IMAGE_UNIFORMS) >= 8 );
		REQUIRE(
			GET(MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS) >=
			GET(MAX_VERTEX_UNIFORM_BLOCKS) *
			GET(MAX_UNIFORM_BLOCK_SIZE) / 4 +
			GET(MAX_VERTEX_UNIFORM_COMPONENTS)
		);
		REQUIRE(
			GET(MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS) >=
			GET(MAX_GEOMETRY_UNIFORM_BLOCKS) *
			GET(MAX_UNIFORM_BLOCK_SIZE) / 4 +
			GET(MAX_GEOMETRY_UNIFORM_COMPONENTS)
		);
		REQUIRE(
			GET(MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS) >=
			GET(MAX_TESS_CONTROL_UNIFORM_BLOCKS) *
			GET(MAX_UNIFORM_BLOCK_SIZE) / 4 +
			GET(MAX_TESS_CONTROL_UNIFORM_COMPONENTS)
		);
		REQUIRE(
			GET(MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS) >=
			GET(MAX_TESS_EVALUATION_UNIFORM_BLOCKS) *
			GET(MAX_UNIFORM_BLOCK_SIZE) / 4 +
			GET(MAX_TESS_EVALUATION_UNIFORM_COMPONENTS)
		);
		REQUIRE(
			GET(MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS) >=
			GET(MAX_FRAGMENT_UNIFORM_BLOCKS) *
			GET(MAX_UNIFORM_BLOCK_SIZE) / 4 +
			GET(MAX_FRAGMENT_UNIFORM_COMPONENTS)
		);
		REQUIRE( GET(DEBUG_LOGGED_MESSAGES) == 0 );
		REQUIRE( GET(DEBUG_NEXT_LOGGED_MESSAGE_LENGTH) == 0 );
		REQUIRE( GET(DEBUG_OUTPUT_SYNCHRONOUS) == true ); // Default to false in the spec, but baregl::Context changes that in debug mode
		REQUIRE( GET(DEBUG_GROUP_STACK_DEPTH) == 1 );
		REQUIRE( GET_WORKS(DEBUG_OUTPUT) );
		REQUIRE( GET(MAX_DEBUG_MESSAGE_LENGTH) >= 1 );
		REQUIRE( GET(MAX_DEBUG_LOGGED_MESSAGES) >= 1 );
		REQUIRE( GET(MAX_DEBUG_GROUP_STACK_DEPTH) >= 64 );
		REQUIRE( GET(MAX_LABEL_LENGTH) >= 256 );

		REQUIRE( GET(MAX_FRAMEBUFFER_WIDTH) >= 16384 );
		REQUIRE( GET(MAX_FRAMEBUFFER_HEIGHT) >= 16384 );
		REQUIRE( GET(MAX_FRAMEBUFFER_LAYERS) >= 2048 );
		REQUIRE( GET(MAX_FRAMEBUFFER_SAMPLES) >= 4 );
		REQUIRE( GET(MAX_SAMPLE_MASK_WORDS) >= 1 );
		REQUIRE( GET(MAX_SAMPLES) >= 4 );
		REQUIRE( GET(MAX_COLOR_TEXTURE_SAMPLES) >= 1 );
		REQUIRE( GET(MAX_DEPTH_TEXTURE_SAMPLES) >= 1 );

		REQUIRE( GET(MAX_INTEGER_SAMPLES) >= 1 );
		REQUIRE( GET_WORKS(MAX_SERVER_WAIT_TIMEOUT) ); // Spec says min is 0, but I get -1
		REQUIRE( GET(MIN_FRAGMENT_INTERPOLATION_OFFSET) <= -0.5 );
		REQUIRE( GET(MAX_FRAGMENT_INTERPOLATION_OFFSET) >= 0.5 );
		REQUIRE( GET(FRAGMENT_INTERPOLATION_OFFSET_BITS) >= 4 );
		REQUIRE( GET(MAX_DRAW_BUFFERS) >= 8 );
		REQUIRE( GET(MAX_DUAL_SOURCE_DRAW_BUFFERS) >= 1 );
		REQUIRE( GET(MAX_COLOR_ATTACHMENTS) >= 8 );
		REQUIRE( GET(MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS) >= 64 );
		REQUIRE( GET(MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS) >= 4 );
		REQUIRE( GET(MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS) >= 4 );
		REQUIRE( GET(MAX_TRANSFORM_FEEDBACK_BUFFERS) >= 4);
		REQUIRE( GET_WORKS(DOUBLEBUFFER) );
		REQUIRE( GET_WORKS(STEREO) );
		REQUIRE( GET(SAMPLE_BUFFERS) >= 0 );
		REQUIRE( GET(SAMPLES) >= 0 );
		// TODO: Enable these when our pixel data format is more comprehensive
		// REQUIRE( GET_WORKS(IMPLEMENTATION_COLOR_READ_FORMAT) );
		// REQUIRE( GET_WORKS(IMPLEMENTATION_COLOR_READ_TYPE) );
		REQUIRE( GET(QUERY_BUFFER_BINDING) == 0 );
		REQUIRE( GET(COPY_READ_BUFFER_BINDING) == 0 );
		REQUIRE( GET(COPY_WRITE_BUFFER_BINDING) == 0 );
		REQUIRE( GET(RESET_NOTIFICATION_STRATEGY) );
		REQUIRE( GET(TEXTURE_BUFFER_BINDING) == 0 );
		REQUIRE( GET(TEXTURE_CUBE_MAP_SEAMLESS) == true ); // Always true, since it's enabled in baregl::Context (for now)
		REQUIRE( GET_WORKS(TIMESTAMP) );
	});
}
