/**
* @project: baregl
* @author: Adrien Givry
* @licence: MIT
*/

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <common/Boilerplate.h>

using namespace tests::common::boilerplate;
using namespace baregl;
using enum baregl::types::EGetParameter;
using namespace baregl::types;

#define QUERY(query, ...) p_context.Get<query>(__VA_ARGS__)
#define QUERY_WORKS(query, ...) (QUERY(query, __VA_ARGS__), true)

TEST_CASE( "Queries return the expected values", "[queries]" ) {
	RunInContext([](GLFWwindow* p_window, Context& p_context) {
		Buffer vbo;
		Buffer ibo;
		Buffer ssbo;
		Buffer ubo;
		Framebuffer fbo;
		VertexArray vao;
		std::array<Buffer, 4> ssbos;
		REQUIRE( QUERY_WORKS(PATCH_VERTICES) );
		REQUIRE( QUERY_WORKS(PATCH_DEFAULT_OUTER_LEVEL) );
		REQUIRE( QUERY_WORKS(PATCH_DEFAULT_INNER_LEVEL) );
		fbo.Unbind();
		REQUIRE( QUERY(ELEMENT_ARRAY_BUFFER_BINDING) == 0 );
		ibo.Bind(EBufferType::INDEX);
		REQUIRE( QUERY(ELEMENT_ARRAY_BUFFER_BINDING) == ibo.GetID() );
		REQUIRE( QUERY_WORKS(VERTEX_BINDING_OFFSET, 0) );
		REQUIRE( QUERY_WORKS(VERTEX_BINDING_STRIDE, 0) );
		REQUIRE( QUERY_WORKS(VERTEX_BINDING_DIVISOR, 0) );
		vao.Unbind();
		REQUIRE( QUERY_WORKS(VERTEX_BINDING_BUFFER, 0) );
		REQUIRE( QUERY_WORKS(VERTEX_BINDING_BUFFER, 0) );
		vbo.Bind(EBufferType::VERTEX);
		REQUIRE( QUERY(ARRAY_BUFFER_BINDING) == vbo.GetID() );
		REQUIRE( QUERY_WORKS(DRAW_INDIRECT_BUFFER_BINDING) );
		REQUIRE( QUERY(VERTEX_ARRAY_BINDING) == 0 );
		vao.Bind();
		REQUIRE( QUERY(VERTEX_ARRAY_BINDING) == vao.GetID() );
		REQUIRE( QUERY_WORKS(PRIMITIVE_RESTART) );
		REQUIRE( QUERY_WORKS(PRIMITIVE_RESTART_FIXED_INDEX) );
		REQUIRE( QUERY(PRIMITIVE_RESTART_INDEX) == 0 );
		p_context.SetViewport(0, 1, 2, 3);
		REQUIRE( QUERY(VIEWPORT) == std::to_array({0,1,2,3}) );
		REQUIRE( QUERY_WORKS(VIEWPORT, 0) );
		// TODO: Add support for indexed viewports
		// REQUIRE( QUERY(VIEWPORT, 1) == std::to_array({0,1,2,3}) );
		REQUIRE( QUERY(DEPTH_RANGE) == std::to_array({0.0, 1.0}) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE0) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE1) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE2) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE3) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE4) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE5) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE6) );
		REQUIRE( QUERY_WORKS(CLIP_DISTANCE7) );
		REQUIRE( QUERY_WORKS(CLIP_ORIGIN) );
		REQUIRE( QUERY_WORKS(CLIP_DEPTH_MODE) );
		REQUIRE( QUERY_WORKS(DEPTH_CLAMP) );
		REQUIRE( QUERY_WORKS(TRANSFORM_FEEDBACK_BINDING) );
		REQUIRE( QUERY_WORKS(CLAMP_READ_COLOR) );
		REQUIRE( QUERY(PROVOKING_VERTEX) == EProvokingVertexConvention::LAST_VERTEX_CONVENTION );
		REQUIRE( QUERY_WORKS(RASTERIZER_DISCARD) );
		REQUIRE( QUERY(POINT_SIZE) == 1.0f );
		REQUIRE( QUERY_WORKS(POINT_FADE_THRESHOLD_SIZE) );
		REQUIRE( QUERY_WORKS(POINT_SPRITE_COORD_ORIGIN) );
		REQUIRE( QUERY(LINE_WIDTH) == 1.0f);
		p_context.SetRasterizationLinesWidth(2.0f);
		REQUIRE( QUERY(LINE_WIDTH) == 2.0f);
		REQUIRE( QUERY(LINE_SMOOTH) == false );
		p_context.SetCapability(ERenderingCapability::LINE_SMOOTH, true);
		REQUIRE( QUERY(LINE_SMOOTH) == true );
		REQUIRE( QUERY(CULL_FACE) == false );
		p_context.SetCapability(ERenderingCapability::CULL_FACE, true);
		REQUIRE( QUERY(CULL_FACE) == true );
		REQUIRE( QUERY(CULL_FACE_MODE) == ECullFace::BACK );
		p_context.SetCullFace(ECullFace::FRONT_AND_BACK);
		REQUIRE( QUERY(CULL_FACE_MODE) == ECullFace::FRONT_AND_BACK );
		REQUIRE( QUERY_WORKS(FRONT_FACE) );
		REQUIRE( QUERY(POLYGON_SMOOTH) == false ); // TODO: How do we enable that??
		REQUIRE( QUERY_WORKS(POLYGON_MODE) );
		REQUIRE( QUERY(POLYGON_OFFSET_FACTOR) == 0.0f );
		REQUIRE( QUERY(POLYGON_OFFSET_UNITS) == 0.0f );
		REQUIRE( QUERY(POLYGON_OFFSET_POINT) == false );
		REQUIRE( QUERY(POLYGON_OFFSET_LINE) == false );
		REQUIRE( QUERY(POLYGON_OFFSET_FILL) == false );
		REQUIRE( QUERY_WORKS(MULTISAMPLE) );
		REQUIRE( QUERY_WORKS(SAMPLE_ALPHA_TO_COVERAGE) );
		REQUIRE( QUERY_WORKS(SAMPLE_ALPHA_TO_ONE) );
		REQUIRE( QUERY_WORKS(SAMPLE_COVERAGE) );
		REQUIRE( QUERY_WORKS(SAMPLE_COVERAGE_VALUE) );
		REQUIRE( QUERY_WORKS(SAMPLE_COVERAGE_INVERT) );
		REQUIRE( QUERY_WORKS(SAMPLE_SHADING) );
		REQUIRE( QUERY_WORKS(MIN_SAMPLE_SHADING_VALUE) );
		REQUIRE( QUERY_WORKS(SAMPLE_MASK) );
		REQUIRE( QUERY_WORKS(SAMPLE_MASK_VALUE) );
		REQUIRE( QUERY(TEXTURE_BINDING_1D) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_2D) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_3D) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_1D_ARRAY) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_2D_ARRAY) == 0 );
		REQUIRE( QUERY_WORKS(TEXTURE_BINDING_CUBE_MAP_ARRAY) );
		REQUIRE( QUERY(TEXTURE_BINDING_RECTANGLE) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_BUFFER) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_CUBE_MAP) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_2D_MULTISAMPLE) == 0 );
		REQUIRE( QUERY(TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY) == 0 );
		REQUIRE( QUERY(SAMPLER_BINDING) == 0 );

		REQUIRE( QUERY(ACTIVE_TEXTURE) == ETextureUnit::TEXTURE0 );
		REQUIRE( QUERY(SCISSOR_TEST) == false );
		p_context.SetCapability(ERenderingCapability::SCISSOR_TEST, true);
		REQUIRE( QUERY(SCISSOR_TEST) == true );
		REQUIRE( QUERY(SCISSOR_BOX)[0] == 0 );
		REQUIRE( QUERY(SCISSOR_BOX)[1] == 0 );
		REQUIRE( QUERY(SCISSOR_BOX)[2] == 256 ); // Window width
		REQUIRE( QUERY(SCISSOR_BOX)[3] == 256 ); // Window height
		REQUIRE( QUERY(STENCIL_TEST) == false );
		REQUIRE( QUERY(STENCIL_FUNC) == EComparaisonAlgorithm::ALWAYS );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( QUERY(STENCIL_VALUE_MASK) == 1 );
		REQUIRE( QUERY(STENCIL_REF) == 0 );
		REQUIRE( QUERY(STENCIL_FAIL) == EOperation::KEEP );
		REQUIRE( QUERY(STENCIL_PASS_DEPTH_FAIL) == EOperation::KEEP );
		REQUIRE( QUERY(STENCIL_PASS_DEPTH_PASS) == EOperation::KEEP );
		REQUIRE( QUERY(STENCIL_BACK_FUNC) == EComparaisonAlgorithm::ALWAYS );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( QUERY(STENCIL_BACK_VALUE_MASK) == 1 );
		REQUIRE( QUERY(STENCIL_BACK_REF) == 0 );
		REQUIRE( QUERY(STENCIL_BACK_FAIL) == EOperation::KEEP );
		REQUIRE( QUERY(STENCIL_BACK_PASS_DEPTH_FAIL) == EOperation::KEEP );
		REQUIRE( QUERY(STENCIL_BACK_PASS_DEPTH_PASS) == EOperation::KEEP );
		REQUIRE( QUERY(DEPTH_TEST) == false );
		p_context.SetCapability(ERenderingCapability::DEPTH_TEST, true);
		REQUIRE( QUERY(DEPTH_TEST) == true );
		REQUIRE( QUERY(DEPTH_FUNC) == EComparaisonAlgorithm::LESS );
		p_context.SetCapability(ERenderingCapability::BLEND, true);
		REQUIRE( QUERY(BLEND) == true );
		p_context.SetBlendingFunction(EBlendingFactor::CONSTANT_ALPHA, EBlendingFactor::CONSTANT_ALPHA);
		REQUIRE( QUERY(BLEND_SRC_RGB) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( QUERY(BLEND_SRC_ALPHA) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( QUERY(BLEND_DST_RGB) == EBlendingFactor::CONSTANT_ALPHA );
		REQUIRE( QUERY(BLEND_DST_ALPHA) == EBlendingFactor::CONSTANT_ALPHA );
		p_context.SetBlendingEquation(EBlendingEquation::FUNC_REVERSE_SUBTRACT);
		REQUIRE( QUERY(BLEND_EQUATION_RGB) == EBlendingEquation::FUNC_REVERSE_SUBTRACT );
		REQUIRE( QUERY(BLEND_EQUATION_ALPHA) == EBlendingEquation::FUNC_REVERSE_SUBTRACT );
		REQUIRE( QUERY(BLEND_COLOR) == std::to_array({0.0f,0.0f,0.0f,0.0f}) );
		REQUIRE( QUERY_WORKS(FRAMEBUFFER_SRGB) );
		REQUIRE( QUERY(DITHER) == true );
		p_context.SetCapability(ERenderingCapability::DITHER, false);
		REQUIRE( QUERY(DITHER) == false );
		REQUIRE( QUERY(COLOR_LOGIC_OP) == false );
		REQUIRE( QUERY(LOGIC_OP_MODE) == ELogicOperation::COPY );
		REQUIRE( QUERY(COLOR_WRITEMASK) == std::to_array({true,true,true,true}) );
		p_context.SetColorWriting(true, false, true, false);
		REQUIRE( QUERY(COLOR_WRITEMASK) == std::to_array({true,false,true,false}) );
		REQUIRE( QUERY(DEPTH_WRITEMASK) == true );
		p_context.SetDepthWriting(false);
		REQUIRE( QUERY(DEPTH_WRITEMASK) == false );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( QUERY(STENCIL_WRITEMASK) == 1 );
		// FIXME: Spec says default value is 1, yet I get -1
		// REQUIRE( QUERY(STENCIL_BACK_WRITEMASK) == 1 );
		REQUIRE( QUERY(COLOR_CLEAR_VALUE) == std::to_array({0.0f,0.0f,0.0f,0.0f}));
		p_context.SetClearColor(0.1f, 0.2f, 0.3f, 0.4f);
		REQUIRE( QUERY(COLOR_CLEAR_VALUE) == std::to_array({0.1f,0.2f,0.3f,0.4f}));
		REQUIRE( QUERY(DEPTH_CLEAR_VALUE) == 1.0 );
		REQUIRE( QUERY(STENCIL_CLEAR_VALUE) == 0 );
		REQUIRE( QUERY(DRAW_FRAMEBUFFER_BINDING) == 0 );
		fbo.Bind();
		REQUIRE( QUERY(DRAW_FRAMEBUFFER_BINDING) == fbo.GetID() );
		REQUIRE( QUERY(READ_FRAMEBUFFER_BINDING) == fbo.GetID() );
		fbo.Unbind();
		REQUIRE( QUERY(DRAW_BUFFER) == EDrawBuffer::BACK );
		REQUIRE( QUERY(DRAW_BUFFER0) == EDrawBuffer::BACK );
		REQUIRE( QUERY(DRAW_BUFFER1) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER2) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER3) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER4) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER5) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER6) == EDrawBuffer::NONE );
		REQUIRE( QUERY(DRAW_BUFFER7) == EDrawBuffer::NONE );
		const auto maxBuffers = QUERY(MAX_DRAW_BUFFERS);
		REQUIRE( (maxBuffers < 9 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 10 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 11 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 12 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 13 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 14 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 15 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( (maxBuffers < 16 || QUERY(DRAW_BUFFER8) == EDrawBuffer::NONE) );
		REQUIRE( QUERY(READ_BUFFER) == EDrawBuffer::BACK );
		fbo.Bind();
		REQUIRE( QUERY(READ_BUFFER) == EDrawBuffer::COLOR_ATTACHMENT0 );
		fbo.Unbind();
		REQUIRE( QUERY(RENDERBUFFER_BINDING) == 0 );
		REQUIRE( QUERY(UNPACK_SWAP_BYTES) == false );
		REQUIRE( QUERY(UNPACK_LSB_FIRST) == false );
		REQUIRE( QUERY(UNPACK_IMAGE_HEIGHT) == 0 );
		REQUIRE( QUERY(UNPACK_SKIP_IMAGES) == 0 );
		REQUIRE( QUERY(UNPACK_ROW_LENGTH) == 0 );
		REQUIRE( QUERY(UNPACK_SKIP_ROWS) == 0 );
		REQUIRE( QUERY(UNPACK_SKIP_PIXELS) == 0 );
		REQUIRE( QUERY(UNPACK_ALIGNMENT) == 4 );
		REQUIRE( QUERY_WORKS(UNPACK_COMPRESSED_BLOCK_WIDTH) );
		REQUIRE( QUERY_WORKS(UNPACK_COMPRESSED_BLOCK_HEIGHT) );
		REQUIRE( QUERY_WORKS(UNPACK_COMPRESSED_BLOCK_DEPTH) );
		REQUIRE( QUERY_WORKS(UNPACK_COMPRESSED_BLOCK_SIZE) );
		REQUIRE( QUERY(PIXEL_UNPACK_BUFFER_BINDING) == 0 );
		REQUIRE( QUERY(PACK_SWAP_BYTES) == false );
		REQUIRE( QUERY(PACK_LSB_FIRST) == false );
		REQUIRE( QUERY(PACK_IMAGE_HEIGHT) == 0 );
		REQUIRE( QUERY(PACK_SKIP_IMAGES) == 0 );
		REQUIRE( QUERY(PACK_ROW_LENGTH) == 0 );
		REQUIRE( QUERY(PACK_SKIP_ROWS) == 0 );
		REQUIRE( QUERY(PACK_SKIP_PIXELS) == 0 );
		REQUIRE( QUERY(PACK_ALIGNMENT) == 4 );
		REQUIRE( QUERY_WORKS(PACK_COMPRESSED_BLOCK_WIDTH) );
		REQUIRE( QUERY_WORKS(PACK_COMPRESSED_BLOCK_HEIGHT) );
		REQUIRE( QUERY_WORKS(PACK_COMPRESSED_BLOCK_DEPTH) );
		REQUIRE( QUERY_WORKS(PACK_COMPRESSED_BLOCK_SIZE) );
		REQUIRE( QUERY(PIXEL_PACK_BUFFER_BINDING) == 0 );
		REQUIRE( QUERY(CURRENT_PROGRAM) == 0 );
		REQUIRE( QUERY(CURRENT_PROGRAM) == 0 );
		REQUIRE( QUERY(PROGRAM_PIPELINE_BINDING) == 0 );
		REQUIRE( QUERY(PROGRAM_POINT_SIZE) == false );
		REQUIRE( QUERY(IMAGE_BINDING_NAME, 1) == 0 );
		REQUIRE( QUERY(IMAGE_BINDING_LEVEL, 1) == 0 );
		REQUIRE( QUERY(IMAGE_BINDING_LAYERED, 1) == false );
		REQUIRE( QUERY(IMAGE_BINDING_LAYER, 1) == 0 );
		REQUIRE( QUERY(IMAGE_BINDING_ACCESS, 1) == EImageAccessSpecifier::READ_ONLY );
		REQUIRE( QUERY(IMAGE_BINDING_FORMAT, 1) == EInternalFormat::R8 );
		REQUIRE( QUERY(ATOMIC_COUNTER_BUFFER_BINDING, 0) == 0 );
		REQUIRE( QUERY(ATOMIC_COUNTER_BUFFER_BINDING) == 0 );
		REQUIRE( QUERY(ATOMIC_COUNTER_BUFFER_START, 0) == 0 );
		REQUIRE( QUERY(ATOMIC_COUNTER_BUFFER_SIZE, 0) == 0 );
		REQUIRE( QUERY(SHADER_STORAGE_BUFFER_BINDING) == 0 );
		ssbo.Bind(EBufferType::SHADER_STORAGE);
		REQUIRE( QUERY(SHADER_STORAGE_BUFFER_BINDING) == ssbo.GetID() );
		ssbo.Unbind();
		for (size_t i = 0; i < 4; ++i)
		{
			ssbos[i].Bind(EBufferType::SHADER_STORAGE, i);
			REQUIRE( QUERY(SHADER_STORAGE_BUFFER_BINDING, i) == ssbos[i].GetID() );
			ssbos[i].Unbind();
		}
		// FIXME: Spec says default value is 0, yet I get 140733763744992
		// REQUIRE( QUERY(SHADER_STORAGE_BUFFER_START) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140733909164800
		// REQUIRE( QUERY(SHADER_STORAGE_BUFFER_SIZE) == 0 );
		REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_BINDING) == 0 );
		REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_BINDING, 0) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140723345732688
		// REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_START) == 0 );
		REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_START, 0) == 0 );
		// FIXME: Spec says default value is 0, yet I get 140736376922736
		// REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_SIZE) == 0 );
		REQUIRE( QUERY(TRANSFORM_FEEDBACK_BUFFER_SIZE, 0) == 0 );
		REQUIRE( QUERY_WORKS(TRANSFORM_FEEDBACK_PAUSED) );
		REQUIRE( QUERY_WORKS(TRANSFORM_FEEDBACK_ACTIVE) );
		REQUIRE( QUERY(UNIFORM_BUFFER_BINDING) == 0 );
		ubo.Bind(types::EBufferType::UNIFORM);
		REQUIRE( QUERY(UNIFORM_BUFFER_BINDING) == ubo.GetID() );
		ubo.Unbind();
		REQUIRE( QUERY(UNIFORM_BUFFER_BINDING, 4) == 0 );
		ubo.Bind(types::EBufferType::UNIFORM, 4);
		REQUIRE( QUERY(UNIFORM_BUFFER_BINDING, 4) == ubo.GetID() );
		REQUIRE( QUERY(UNIFORM_BUFFER_START, 0) == 0 );
		REQUIRE( QUERY(UNIFORM_BUFFER_SIZE, 0) == 0 );
		REQUIRE( QUERY(LINE_SMOOTH_HINT) == EHint::DONT_CARE );
		REQUIRE( QUERY(POLYGON_SMOOTH_HINT) == EHint::DONT_CARE );
		REQUIRE( QUERY(TEXTURE_COMPRESSION_HINT) == EHint::DONT_CARE );
		REQUIRE( QUERY(FRAGMENT_SHADER_DERIVATIVE_HINT) == EHint::DONT_CARE );

		REQUIRE( QUERY(DISPATCH_INDIRECT_BUFFER_BINDING) == 0 );
		REQUIRE( QUERY_WORKS(CONTEXT_RELEASE_BEHAVIOR) );
		REQUIRE( QUERY(MAX_CLIP_DISTANCES) >= 8 );
		REQUIRE( QUERY(MAX_CULL_DISTANCES) >= 8 );
		REQUIRE( QUERY(MAX_COMBINED_CLIP_AND_CULL_DISTANCES) >= 8 );
		REQUIRE( QUERY(SUBPIXEL_BITS) >= 4 );
		REQUIRE( QUERY(MAX_ELEMENT_INDEX) >= (1LL << 32) - 1 );
		REQUIRE( QUERY_WORKS(PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED) );
		REQUIRE( QUERY(MAX_3D_TEXTURE_SIZE) >= 2048 );
		REQUIRE( QUERY(MAX_TEXTURE_SIZE) >= 16384 );
		REQUIRE( QUERY(MAX_ARRAY_TEXTURE_LAYERS) >= 2048 );
		REQUIRE( QUERY(MAX_TEXTURE_LOD_BIAS) >= 2.0f );
		REQUIRE( QUERY(MAX_CUBE_MAP_TEXTURE_SIZE) >= 16384 );
		REQUIRE( QUERY(MAX_RENDERBUFFER_SIZE) >= 16384 );
		REQUIRE( QUERY(MAX_VIEWPORT_DIMS)[0] >= QUERY(MAX_RENDERBUFFER_SIZE) );
		REQUIRE( QUERY(MAX_VIEWPORT_DIMS)[1] >= QUERY(MAX_RENDERBUFFER_SIZE) );
		REQUIRE( QUERY(MAX_VIEWPORTS) >= 16 );
		REQUIRE( QUERY(VIEWPORT_SUBPIXEL_BITS) >= 0 );
		REQUIRE( QUERY(VIEWPORT_BOUNDS_RANGE)[0] <= -32768.0f );
		REQUIRE( QUERY(VIEWPORT_BOUNDS_RANGE)[1] >= 32767.0f );
		// FIXME: Value not found in mapping
		// REQUIRE( QUERY_WORKS(LAYER_PROVOKING_VERTEX) );
		REQUIRE( QUERY_WORKS(VIEWPORT_INDEX_PROVOKING_VERTEX) );
		REQUIRE( QUERY(POINT_SIZE_RANGE)[0] <= 1.0f );
		REQUIRE( QUERY(POINT_SIZE_RANGE)[1] >= 1.0f );
		REQUIRE( QUERY_WORKS(POINT_SIZE_GRANULARITY) );
		REQUIRE( QUERY(ALIASED_LINE_WIDTH_RANGE)[0] <= 1.0f );
		REQUIRE( QUERY(ALIASED_LINE_WIDTH_RANGE)[1] >= 1.0f );
		REQUIRE( QUERY(SMOOTH_LINE_WIDTH_RANGE)[0] <= 1.0f );
		REQUIRE( QUERY(SMOOTH_LINE_WIDTH_RANGE)[1] >= 1.0f );
		REQUIRE( QUERY_WORKS(SMOOTH_LINE_WIDTH_GRANULARITY) );
		REQUIRE( QUERY_WORKS(MAX_ELEMENTS_INDICES) );
		REQUIRE( QUERY_WORKS(MAX_ELEMENTS_VERTICES) );	
		REQUIRE( QUERY(MAX_VERTEX_ATTRIB_RELATIVE_OFFSET) >= 2047 );
		REQUIRE( QUERY(MAX_VERTEX_ATTRIB_BINDINGS) >= 16 );
		REQUIRE( QUERY(MAX_VERTEX_ATTRIB_STRIDE) >= 2048 );
		REQUIRE( QUERY(NUM_COMPRESSED_TEXTURE_FORMATS) >= 12 ); // Should be 18 according to the specs, but some implementations aren't fully compliant (which is the case for baregl's CI runner)
		REQUIRE( QUERY(COMPRESSED_TEXTURE_FORMATS).size() == QUERY(NUM_COMPRESSED_TEXTURE_FORMATS) );
		REQUIRE( QUERY(MAX_TEXTURE_BUFFER_SIZE) >= 65536 );
		REQUIRE( QUERY(MAX_RECTANGLE_TEXTURE_SIZE) >= 16384 );
		REQUIRE( QUERY(NUM_PROGRAM_BINARY_FORMATS) >= 0 );
		REQUIRE( QUERY(PROGRAM_BINARY_FORMATS).size() == QUERY(NUM_PROGRAM_BINARY_FORMATS) );
		REQUIRE( QUERY(NUM_SHADER_BINARY_FORMATS) >= 0 );
		REQUIRE( QUERY(SHADER_BINARY_FORMATS).size() == QUERY(NUM_SHADER_BINARY_FORMATS) );
		REQUIRE( QUERY(SHADER_COMPILER) == true );
		REQUIRE( QUERY(MIN_MAP_BUFFER_ALIGNMENT) >= 64 ); // Must be power of 2
		REQUIRE( QUERY(TEXTURE_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( QUERY(MAJOR_VERSION) == 4 );
		REQUIRE( QUERY(MINOR_VERSION) == 5 );
		REQUIRE( QUERY(CONTEXT_FLAGS) == EContextFlags::DEBUG_BIT );
		REQUIRE( QUERY_WORKS(CONTEXT_PROFILE_MASK) );
		REQUIRE( QUERY(EXTENSIONS).size() == QUERY(NUM_EXTENSIONS) );
		REQUIRE( QUERY_WORKS(NUM_EXTENSIONS) );
		REQUIRE( QUERY_WORKS(RENDERER) );
		REQUIRE( QUERY_WORKS(SHADING_LANGUAGE_VERSION) );
		// FIXME: Retrieval doesn't seem to work properly (dynamic with different query param issue?)
		// REQUIRE( QUERY(SHADING_LANGUAGE_VERSIONS).size() == QUERY(NUM_SHADING_LANGUAGE_VERSIONS) );
		// for (auto& version : QUERY(SHADING_LANGUAGE_VERSIONS))
		// {
		// 	printf("Version: %s\n", version.c_str());
		// }
		// REQUIRE_FALSE(true);
		REQUIRE( QUERY(NUM_SHADING_LANGUAGE_VERSIONS) >= 3 );
		REQUIRE( QUERY_WORKS(VENDOR) );
		REQUIRE( QUERY_WORKS(VERSION) );
		REQUIRE( QUERY(MAX_VERTEX_ATTRIBS) >= 16 );
		REQUIRE( QUERY(MAX_VERTEX_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_VERTEX_UNIFORM_VECTORS) >= 256 );
		REQUIRE( QUERY(MAX_VERTEX_UNIFORM_VECTORS) == QUERY(MAX_VERTEX_UNIFORM_COMPONENTS) / 4 );
		REQUIRE( QUERY(MAX_VERTEX_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( QUERY(MAX_VERTEX_OUTPUT_COMPONENTS) >= 64 );
		REQUIRE( QUERY(MAX_VERTEX_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MAX_VERTEX_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( QUERY(MAX_VERTEX_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( QUERY(MAX_VERTEX_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( QUERY(MAX_TESS_GEN_LEVEL) >= 64 );
		REQUIRE( QUERY(MAX_PATCH_VERTICES) >= 32 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY(MAX_TESS_PATCH_COMPONENTS) >= 120 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS) >= 4096 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_INPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY_WORKS(MAX_TESS_CONTROL_UNIFORM_BLOCKS) );
		REQUIRE( QUERY(MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( QUERY(MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( QUERY(MAX_TESS_EVALUATION_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_INPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( QUERY(MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( QUERY(MAX_GEOMETRY_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_GEOMETRY_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( QUERY(MAX_GEOMETRY_INPUT_COMPONENTS) >= 64 );
		REQUIRE( QUERY(MAX_GEOMETRY_OUTPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY(MAX_GEOMETRY_OUTPUT_VERTICES) >= 256 );
		REQUIRE( QUERY(MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_GEOMETRY_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MAX_GEOMETRY_SHADER_INVOCATIONS) >= 32 );
		REQUIRE( QUERY(MAX_VERTEX_STREAMS) >= 4 );
		REQUIRE( QUERY(MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS) >= 0 );
		REQUIRE( QUERY(MAX_GEOMETRY_ATOMIC_COUNTERS) >= 0 );
		REQUIRE( QUERY(MAX_GEOMETRY_SHADER_STORAGE_BLOCKS) >= 0 );

		REQUIRE( QUERY(MAX_FRAGMENT_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_FRAGMENT_UNIFORM_VECTORS) >= QUERY(MAX_FRAGMENT_UNIFORM_COMPONENTS) / 4 );
		REQUIRE( QUERY(MAX_FRAGMENT_UNIFORM_VECTORS) >= 256 );
		REQUIRE( QUERY(MAX_FRAGMENT_UNIFORM_BLOCKS) >= 14 );
		REQUIRE( QUERY(MAX_FRAGMENT_INPUT_COMPONENTS) >= 128 );
		REQUIRE( QUERY(MAX_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MIN_PROGRAM_TEXTURE_GATHER_OFFSET) <= -8 );
		REQUIRE( QUERY(MAX_PROGRAM_TEXTURE_GATHER_OFFSET) >= 7 );
		REQUIRE( QUERY(MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS) >= 1 );
		REQUIRE( QUERY(MAX_FRAGMENT_ATOMIC_COUNTERS) >= 8 );
		REQUIRE( QUERY(MAX_FRAGMENT_SHADER_STORAGE_BLOCKS) >= 8 );

		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_COUNT, 0) >= 65535 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_COUNT, 1) >= 65535 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_COUNT, 2) >= 65535 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_SIZE, 0) >= 1024 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_SIZE, 1) >= 1024 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_SIZE, 2) >= 64 );
		REQUIRE( QUERY(MAX_COMPUTE_WORK_GROUP_INVOCATIONS) >= 1024 );
		REQUIRE( QUERY(MAX_COMPUTE_UNIFORM_BLOCKS) >= 11 ); // Spec says 14 is minimum, but some driver implementations have lower values
		REQUIRE( QUERY(MAX_COMPUTE_TEXTURE_IMAGE_UNITS) >= 16 );
		REQUIRE( QUERY(MAX_COMPUTE_ATOMIC_COUNTERS) >= 8 );
		REQUIRE( QUERY(MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS) >= 8 );
		REQUIRE( QUERY(MAX_COMPUTE_SHARED_MEMORY_SIZE) >= 32768 );
		REQUIRE( QUERY(MAX_COMPUTE_UNIFORM_COMPONENTS) >= 1024 );
		REQUIRE( QUERY(MAX_COMPUTE_IMAGE_UNIFORMS) >= 8 );
		REQUIRE( QUERY(MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS) >= 0 ); // Spec says "*"?
		REQUIRE( QUERY(MAX_COMPUTE_SHADER_STORAGE_BLOCKS) >= 8 );
		REQUIRE( QUERY(MIN_PROGRAM_TEXEL_OFFSET) <= -8 );
		REQUIRE( QUERY(MAX_PROGRAM_TEXEL_OFFSET) >= 7 );
		REQUIRE( QUERY(MAX_UNIFORM_BUFFER_BINDINGS) >= 36 );
		REQUIRE( QUERY(MAX_UNIFORM_BLOCK_SIZE) >= 16384 );
		ubo.Unbind();
		REQUIRE( QUERY(UNIFORM_BUFFER_OFFSET_ALIGNMENT) >= 1 );
		REQUIRE( QUERY(UNIFORM_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( QUERY(MAX_COMBINED_UNIFORM_BLOCKS) >= 70 );
		REQUIRE( QUERY(MAX_VARYING_COMPONENTS) >= 60 );
		REQUIRE( QUERY(MAX_VARYING_VECTORS) >= 15 );
		REQUIRE( QUERY(MAX_VARYING_VECTORS) == QUERY(MAX_VARYING_COMPONENTS) / 4);
		REQUIRE( QUERY(MAX_VARYING_FLOATS) >= 32 );
		REQUIRE( QUERY(MAX_COMBINED_TEXTURE_IMAGE_UNITS) >= 48 );
		REQUIRE( QUERY_WORKS(MAX_SUBROUTINES) );
		REQUIRE( QUERY_WORKS(MAX_SUBROUTINE_UNIFORM_LOCATIONS) );
		REQUIRE( QUERY(MAX_UNIFORM_LOCATIONS) >= 1024 );
		REQUIRE( QUERY_WORKS(MAX_ATOMIC_COUNTER_BUFFER_BINDINGS) );
		REQUIRE( QUERY_WORKS(MAX_ATOMIC_COUNTER_BUFFER_SIZE) );
		REQUIRE( QUERY_WORKS(MAX_COMBINED_ATOMIC_COUNTER_BUFFERS) );
		REQUIRE( QUERY(MAX_COMBINED_ATOMIC_COUNTERS) >= 8 ); // Heuristic (https://opengl.gpuinfo.org)
		REQUIRE( QUERY(MAX_SHADER_STORAGE_BUFFER_BINDINGS) >= 8 );
		REQUIRE( QUERY_WORKS(MAX_SHADER_STORAGE_BLOCK_SIZE) );

		REQUIRE( QUERY(MAX_COMBINED_SHADER_STORAGE_BLOCKS) >= 8 );
		REQUIRE( QUERY(SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT) >= 1 );
		REQUIRE( QUERY(SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT) <= 256 );
		REQUIRE( QUERY_WORKS(MAX_IMAGE_UNITS) );
		REQUIRE( QUERY_WORKS(MAX_COMBINED_SHADER_OUTPUT_RESOURCES) );
		REQUIRE( QUERY_WORKS(MAX_IMAGE_SAMPLES) );
		REQUIRE( QUERY_WORKS(MAX_VERTEX_IMAGE_UNIFORMS) );
		REQUIRE( QUERY_WORKS(MAX_TESS_CONTROL_IMAGE_UNIFORMS) );
		REQUIRE( QUERY_WORKS(MAX_TESS_EVALUATION_IMAGE_UNIFORMS) );
		REQUIRE( QUERY_WORKS(MAX_GEOMETRY_IMAGE_UNIFORMS) );
		REQUIRE( QUERY_WORKS(MAX_FRAGMENT_IMAGE_UNIFORMS) );
		REQUIRE( QUERY_WORKS(MAX_COMBINED_IMAGE_UNIFORMS) );
		REQUIRE( QUERY(MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS) >= 1 );
		REQUIRE( QUERY(MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS) >= 1 );
		REQUIRE( QUERY_WORKS(MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS) );
		REQUIRE( QUERY_WORKS(MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS) );
		REQUIRE( QUERY(MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS) >= 1);
		REQUIRE( QUERY_WORKS(DEBUG_LOGGED_MESSAGES) );
		REQUIRE( QUERY_WORKS(DEBUG_NEXT_LOGGED_MESSAGE_LENGTH) );
		REQUIRE( QUERY_WORKS(DEBUG_OUTPUT_SYNCHRONOUS) );
		REQUIRE( QUERY(DEBUG_GROUP_STACK_DEPTH) >= 0 );
		REQUIRE( QUERY_WORKS(DEBUG_OUTPUT) );
		REQUIRE( QUERY_WORKS(MAX_DEBUG_MESSAGE_LENGTH) );
		REQUIRE( QUERY_WORKS(MAX_DEBUG_LOGGED_MESSAGES) );
		REQUIRE( QUERY(MAX_DEBUG_GROUP_STACK_DEPTH) >= 64 ); // Heuristic (https://opengl.gpuinfo.org)
		REQUIRE( QUERY(MAX_LABEL_LENGTH) >= 256 ); // Heuristic (https://opengl.gpuinfo.org)

		REQUIRE( QUERY(MAX_FRAMEBUFFER_WIDTH) >= 16384 );
		REQUIRE( QUERY(MAX_FRAMEBUFFER_HEIGHT) >= 16384 );
		REQUIRE( QUERY(MAX_FRAMEBUFFER_LAYERS) >= 2048 );
		REQUIRE( QUERY(MAX_FRAMEBUFFER_SAMPLES) >= 4 );
		REQUIRE( QUERY(MAX_SAMPLE_MASK_WORDS) >= 1 ); // Heuristic (https://opengl.gpuinfo.org)
		REQUIRE( QUERY_WORKS(MAX_SAMPLES) );
		REQUIRE( QUERY(MAX_COLOR_TEXTURE_SAMPLES) >= 4 ); // Heuristic (https://opengl.gpuinfo.org)
		REQUIRE( QUERY(MAX_DEPTH_TEXTURE_SAMPLES) >= 4 ); // Heuristic (https://opengl.gpuinfo.org)

		REQUIRE( QUERY(MAX_INTEGER_SAMPLES) >= 1 ); // Heuristic (https://opengl.gpuinfo.org)
		REQUIRE( QUERY_WORKS(MAX_SERVER_WAIT_TIMEOUT) );
		REQUIRE( QUERY_WORKS(MIN_FRAGMENT_INTERPOLATION_OFFSET) );
		REQUIRE( QUERY_WORKS(MAX_FRAGMENT_INTERPOLATION_OFFSET) );
		REQUIRE( QUERY_WORKS(FRAGMENT_INTERPOLATION_OFFSET_BITS) );
		REQUIRE( QUERY(MAX_DRAW_BUFFERS) >= 8 );
		REQUIRE( QUERY(MAX_DUAL_SOURCE_DRAW_BUFFERS) >= 1 );
		REQUIRE( QUERY_WORKS(MAX_COLOR_ATTACHMENTS) );
		REQUIRE( QUERY_WORKS(MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS) );
		REQUIRE( QUERY_WORKS(MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS) );
		REQUIRE( QUERY_WORKS(MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS) );
		REQUIRE( QUERY_WORKS(MAX_TRANSFORM_FEEDBACK_BUFFERS) );
		REQUIRE( QUERY_WORKS(DOUBLEBUFFER) );
		REQUIRE( QUERY_WORKS(STEREO) );
		REQUIRE( QUERY_WORKS(SAMPLE_BUFFERS) );
		REQUIRE( QUERY_WORKS(SAMPLES) );
		// TODO: Enable these when our pixel data format is more comprehensive
		// REQUIRE( QUERY_WORKS(IMPLEMENTATION_COLOR_READ_FORMAT) );
		// REQUIRE( QUERY_WORKS(IMPLEMENTATION_COLOR_READ_TYPE) );
		REQUIRE( QUERY_WORKS(QUERY_BUFFER_BINDING) );
		REQUIRE( QUERY_WORKS(COPY_READ_BUFFER_BINDING) );
		REQUIRE( QUERY_WORKS(COPY_WRITE_BUFFER_BINDING) );
		REQUIRE( QUERY_WORKS(RESET_NOTIFICATION_STRATEGY) );
		REQUIRE( QUERY_WORKS(TEXTURE_BUFFER_BINDING) );
		REQUIRE( QUERY_WORKS(TEXTURE_CUBE_MAP_SEAMLESS) );
		REQUIRE( QUERY_WORKS(TIMESTAMP) );
	});
}
